# 00 Firm Selection

This notebook identifies three French environmental, sustainability, or carbon-related organizations with published BEGES reports on the ADEME platform.

The selected firms will be used for a comparative GHG inventory and reporting-quality analysis in the `bilan-critique` project.

This notebook uses the ADEME open-data export and DuckDB so that the firm selection process is reproducible, transparent, and based on SQL queries rather than manual searching alone.

In [33]:
import duckdb
import pandas as pd
from pathlib import Path

conn = duckdb.connect()

csv_path = Path("../data/raw/export-opendata-inventories-03-05-2026.csv")

print("Libraries loaded successfully")
print(csv_path.exists())

Libraries loaded successfully
True

## Load the ADEME BEGES export

This block loads the raw ADEME BEGES export into a pandas dataframe.

The ADEME file uses semicolons as column separators, which is common in French open-data CSV files. The dataset is loaded without modification so that the original structure is preserved.

The shape of the dataframe is printed to confirm the number of rows and columns. The first rows are displayed to verify that the file loaded correctly.

In [34]:
df = pd.read_csv(csv_path, sep=";", low_memory=False)

print(df.shape)

df.head()

(11138, 104)

,Id,"Méthode BEGES (V4,V5)",Date de publication,Type de structure,Type de collectivité,Raison sociale,SIREN principal,APE(NAF) associé,Libellé,Nombre de salariés/d'agents de l'ensemble des SIREN déclarés sur ce bilan lors de l'année de reporting du bilan,...,Incertitudes,Sources,Recalcul,Siret,Comparaison avec le précédent bilan,Lien URL vers le rapport complet du BEGES,Responsable du suivi,Fonction,Téléphone,Courriel
0,503c7fae-4344-4957-b7bc-d891c186d647,v5,01/01/2025,Entreprise,NaN,SERIDERM FRANCE,843307646,4645Z,Commerce de gros (commerce interentreprises) d...,Entre 20 et 49,...,NaN,Les principales sources de facteurs d&#039;émi...,NaN,84330764600029,NaN,NaN,[Masqué],[Masqué],[Masqué],[Masqué]
1,9381ca45-b1cd-11ed-8fce-005056b7acd1,v4,01/02/2017,Établissement public,NaN,CENTRE HOSPITALIER DE LA COTE FLEURIE,200017986,8610Z,Activités hospitalières,Entre 500 et 999,...,l&#039;incertitude sur le bilan global est de ...,NaN,NaN,NaN,NaN,NaN,[Masqué],[Masqué],[Masqué],[Masqué]
2,9381cdd9-b1cd-11ed-8fce-005056b7acd1,v4,01/02/2017,Entreprise,NaN,AREVA NP SAS,428764500,2530Z,"Fabrication de générateurs de vapeur, à l'exce...",Entre 5 000 et 9 999,...,NaN,NaN,NaN,NaN,NaN,NaN,Maxime PILLIE,Responsable Développement Durable et RSE,NaN,maxime.pillie@areva.com
3,9381cfcc-b1cd-11ed-8fce-005056b7acd1,v4,01/02/2017,Entreprise,NaN,GROUPE SECOB RENNES,424936656,6920Z,Activités comptables,Entre 50 et 99,...,NaN,NaN,NaN,NaN,NaN,NaN,[Masqué],[Masqué],[Masqué],[Masqué]
4,937cbcaf-b1cd-11ed-8fce-005056b7acd1,v4,01/02/2017,Entreprise,NaN,GROUPAMA D'OC,391851557,6512Z,Autres assurances,Entre 1 000 et 1 999,...,\n\t\n\t\t\n\t\t\t\n\t\t\tPoste d’émissions\n\...,NaN,NaN,\r\n\t\r\n\t\t\r\n\t\t\tENTREPRISE\r\n\t\t\tSI...,NaN,NaN,[Masqué],[Masqué],[Masqué],[Masqué]

In [35]:
df.shape

(11138, 104)

## Inspect available columns

This block displays the column names in the ADEME export.

Before writing SQL queries, the exact column names must be inspected because the dataset uses French administrative labels. These names will be used to filter organizations, reporting years, emissions scopes, and business sectors.

In [36]:
df.columns.tolist()

['Id',
 'Méthode BEGES (V4,V5)',
 'Date de publication',
 'Type de structure',
 'Type de collectivité',
 'Raison sociale',
 'SIREN principal',
 'APE(NAF) associé',
 'Libellé',
 "Nombre de salariés/d'agents de l'ensemble des SIREN déclarés sur ce bilan lors de l'année de reporting du bilan",
 'Population',
 'Région',
 'Code département',
 'Département',
 'Structure obligée',
 'SIREN des entités consolidées',
 'Code NAF des entités consolidées',
 'Départements des entités consolidées',
 'Statut des entités consolidées',
 'Mode de consolidation',
 'Année de reporting',
 'Assujetti DPEF/PCAET ?',
 'Lien DPEF/PCAET',
 'Assujetti à la CSRD',
 'Périmètre national décrit dans CSRD',
 'Lien CSRD',
 'Pages CSRD correspondantes',
 "Aide diag décarbon'action",
 "Seuil d'importance retenu (%)",
 "Niveau d'influence",
 'Importance stratégique et vulnérabilités',
 'Lignes directrices spécifiques au secteur',
 'Sous-traitance',
 'Engagement du personnel',
 "Justification des postes d'émissions indirectes écartés",
 'Emissions publication P1.1',
 'Emissions publication P1.2',
 'Emissions publication P1.3',
 'Emissions publication P1.4',
 'Emissions publication P1.5',
 'Emissions publication P2.1',
 'Emissions publication P2.2',
 'Emissions publication P3.1',
 'Emissions publication P3.2',
 'Emissions publication P3.3',
 'Emissions publication P3.4',
 'Emissions publication P3.5',
 'Emissions publication P4.1',
 'Emissions publication P4.2',
 'Emissions publication P4.3',
 'Emissions publication P4.4',
 'Emissions publication P4.5',
 'Emissions publication P5.1',
 'Emissions publication P5.2',
 'Emissions publication P5.3',
 'Emissions publication P5.4',
 'Emissions publication P6.1',
 'Une année de référence a été calculée',
 'Année de référence',
 'Emissions référence P1.1',
 'Emissions référence P1.2',
 'Emissions référence P1.3',
 'Emissions référence P1.4',
 'Emissions référence P1.5',
 'Emissions référence P2.1',
 'Emissions référence P2.2',
 'Emissions référence P3.1',
 'Emissions référence P3.2',
 'Emissions référence P3.3',
 'Emissions référence P3.4',
 'Emissions référence P3.5',
 'Emissions référence P4.1',
 'Emissions référence P4.2',
 'Emissions référence P4.3',
 'Emissions référence P4.4',
 'Emissions référence P4.5',
 'Emissions référence P5.1',
 'Emissions référence P5.2',
 'Emissions référence P5.3',
 'Emissions référence P5.4',
 'Emissions référence P6.1',
 "Présentation de l'organisation",
 'Politique Développement Durable',
 'Réduction attendue des émissions directes',
 'Réduction attendue des émissions indirectes significatives',
 'Objectif de réduction pour 2030',
 'Objectif de réduction pour 2050',
 'Objectif de réduction à d’autres horizons temporels',
 'Actions et moyens',
 'Analyse des résultats obtenus',
 'Des émissions évitées ont été calculées pour',
 "Part de l'énergie garantie d'origine et/ou renouvelable dans la consommation d'énergie",
 "Complément d'information sur les énergies garanties d'origine et/ou renouvelables",
 'Liste des facteurs d’émission (FE) et Pouvoir de Réchauffement Global (PRG) utilisés',
 'Incertitudes',
 'Sources',
 'Recalcul',
 'Siret',
 'Comparaison avec le précédent bilan',
 'Lien URL vers le rapport complet du BEGES',
 'Responsable du suivi',
 'Fonction',
 'Téléphone',
 'Courriel']

## Register the ADEME dataframe as a SQL table

This block registers the raw ADEME dataframe as a DuckDB table named `beges`.

This allows the notebook to query the dataset using SQL. SQL is useful here because the first project task is not visualization, but structured filtering: identifying organizations by type, sector, reporting year, CSRD status, and emissions completeness.

In [37]:
conn.register("beges", df)

conn.sql("""
SELECT 
    "Type de structure",
    COUNT(*) AS number_of_reports
FROM beges
GROUP BY "Type de structure"
ORDER BY number_of_reports DESC
""").df()

                       Type de structure  number_of_reports
0                             Entreprise               7820
1                   Établissement public               1876
2  Collectivité territoriale (dont EPCI)                738
3                                   État                392
4                            Association                312

## Search the full ADEME dataset for candidate organizations

This block searches the complete ADEME dataset for organizations whose names suggest a connection to carbon, sustainability, climate consulting, environmental consulting, or technical environmental services.

At this stage, no structure type is excluded. This avoids accidentally removing relevant organizations that may be registered as associations, public entities, or another legal category.

In [38]:
candidate_search = conn.sql("""
SELECT
    "Id",
    "Raison sociale",
    "Type de structure",
    "Libellé",
    "Année de reporting",
    "Assujetti à la CSRD",
    "Nombre de salariés/d'agents de l'ensemble des SIREN déclarés sur ce bilan lors de l'année de reporting du bilan" AS staff_count,
    "Emissions publication P1.1",
    "Emissions publication P2.1",
    "Emissions publication P3.1",
    "Emissions publication P4.1",
    "Emissions publication P5.1",
    "Lien URL vers le rapport complet du BEGES"
FROM beges
WHERE UPPER("Raison sociale") LIKE '%CARBONE%'
   OR UPPER("Raison sociale") LIKE '%CLIMAT%'
   OR UPPER("Raison sociale") LIKE '%ENVIRON%'
   OR UPPER("Raison sociale") LIKE '%GREEN%'
   OR UPPER("Raison sociale") LIKE '%ECO%'
   OR UPPER("Raison sociale") LIKE '%DURABLE%'
   OR UPPER("Raison sociale") LIKE '%SUSTAIN%'
ORDER BY "Année de reporting" DESC
""").df()

candidate_search.shape

(268, 13)

## Review keyword search results

This block displays the candidate organizations found through the initial keyword search.

The goal is to inspect whether the search is finding relevant carbon, sustainability, climate, and environmental organizations before applying stricter selection criteria.

In [39]:
candidate_search[
    [
        "Id",
        "Raison sociale",
        "Type de structure",
        "Libellé",
        "Année de reporting",
        "staff_count",
        "Assujetti à la CSRD"
    ]
].head(50)

,Id,Raison sociale,Type de structure,Libellé,Année de reporting,staff_count,Assujetti à la CSRD
0,a5f95a32-b811-4799-9818-f513dab0af38,TECHNI DECO S.A,Entreprise,Décolletage,2025,22,non
1,4ee63981-b1d8-47c1-92e5-69afe64bff85,ECOLE NATIONALE SUPERIEURE D'ARCHITECTURE ET D...,Établissement public,Enseignement supérieur,2025,150,NaN
2,b4d841bd-4b7a-477a-a3d9-f4cd7a12ec57,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,Établissement public,Enseignement supérieur,2025,147,NaN
3,ef76b5b1-82e7-47f4-a483-a52772e0e436,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,Services du feu et de secours,2024,4159,NaN
4,f36d813e-ccff-4147-94d4-8ab88799e206,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,"Administration publique (tutelle) de la santé,...",2024,1352,NaN
5,ddcb866a-51d5-4454-ac79-03d46719d0c8,"Direction régionale de l'environnement, de l'a...",État,Administration publique (tutelle) des activité...,2024,700,NaN
6,95a9d2c8-2be5-4d42-a5c0-4950a2a57ce8,SCOP EcoZimut,Entreprise,"Ingénierie, études techniques",2024,16,NaN
7,f166a771-2254-4a82-9b2c-034767471655,INSTITUT ENSEIGNEMENT SUPERIEUR ET RECHERCHE E...,Établissement public,Enseignement supérieur,2024,652,NaN
8,955a190b-6400-4b61-8566-97eb2ef1a8d1,ASSOCIATION ESTP - GRANDE ECOLE D'INGENIEURS D...,Association,Enseignement supérieur,2024,246,non
9,d70a0f1c-b69c-4600-994b-80d1c903b8b5,ECOCERT SA,Entreprise,"Analyses, essais et inspections techniques",2024,778,NaN
10,d9c0420a-36de-4b60-bf07-4f1fa08e7aa5,SECOGES,Entreprise,Activités comptables,2024,57,NaN
11,4be1d0f9-9eac-439a-b802-647554254c56,Ecole Nationale des Sports de Montagne,Établissement public,Enseignement supérieur,2024,193,NaN
12,c45297ef-cfbe-4ae8-9d65-864146e92f9c,SCE DEPARTEMENTAL INCENDIE ET SECOURS DU TARN,Établissement public,Services du feu et de secours,2024,320,NaN
13,17cf5926-6b43-4231-9f83-37a1fe1934e9,GREEN OUTSIDE,Entreprise,Commerce de gros (commerce interentreprises) n...,2024,9,NaN
14,81f43d39-94f8-4f0a-91b9-88ec9ad822af,SERVICE INCENDIE ET SECOURS DU HAUT-RHIN,Établissement public,Services du feu et de secours,2024,561,NaN
15,b2854ede-20b9-47bc-b2da-3e660e9cfb0c,TEXDECOR SAS,Entreprise,Commerce de gros (commerce interentreprises) d...,2024,390,NaN
16,d21a2c7c-c9da-4bb5-9f3a-93d412b0d4aa,ECOLE DE CONDE,Entreprise,Enseignement supérieur,2024,216,non
17,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non
18,0e05e00a-25ba-431c-b02d-4715b7617a37,ECOLE NATIONALE SUPERIEURE MARITIME,Établissement public,Enseignement supérieur,2024,235,NaN
19,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non
20,77a34eb1-4899-465c-8e13-4d8513a20544,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,Services du feu et de secours,2024,1800,NaN
21,550db72c-474a-4c75-a1f6-869ee3da57bb,Secrétariat Général des Ministères Economiques...,État,Administration publique générale,2024,11036,NaN
22,7a0b6f91-9d03-4851-a2cc-9f2ab53b21d5,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,"Analyses, essais et inspections techniques",2024,890,NaN
23,6bbe2e1a-33ac-4b1f-bc4a-835185c805de,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,Services du feu et de secours,2024,417,NaN
24,84b36b10-374e-4ef6-91a2-9e88eeef528c,AGENCE DE L ENVIRONNEMENT ET DE LA MAITRISE DE...,Établissement public,Administration publique (tutelle) des activité...,2024,1395,NaN
25,fec73e74-acc2-4a16-b246-eb7414c43c02,Centre hospitalier de CREVECOEUR-LE-GRAND,Établissement public,Activités hospitalières,2024,273,NaN
26,cf7f2d17-758f-425e-9107-1b977e734a40,ECOLE NATIONALE DE LA MAGISTRATURE,Établissement public,Enseignement supérieur,2024,285,NaN
27,8e3e5052-07cb-4e79-b3b7-6050d4e10d5a,Wagner Environnement Travaux Publics (WETP),Entreprise,Travaux de terrassement courants et travaux pr...,2024,38,NaN
28,38351f60-1ae3-46f8-8d60-ea2256abd70a,SFECO SOLUTIONS,Entreprise,Construction de réseaux électriques et de télé...,2024,55,NaN
29,781d04cf-5d85-4e85-8c9f-e3feed661d62,Econocom,Entreprise,Location et location-bail de machines de burea...,2024,8446,oui
30,0a7283f1-d32f-4a60-b3b8-6410e1b8f00b,GESTECO,Entreprise,Services administratifs combinés de bureau,2024,150,non
31,101e16be-9d48-4355-bacb-da23d6e1556d,Grenoble Ecole de Management,Entreprise,Enseignement supérieur,2024,420,NaN
32,1b6841fe-706b-4226-b83c-accbc3b87ecf,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,Services du feu et de secours,2024,2703,NaN
33,5e1dcbd9-1848-4e05-a510-ef28436ed9ea,SAS OBJECTIF ZERO CARBONE CONSULTING (CARBONO),Entreprise,"Activités spécialisées, scientifiques et techn...",2024,6,NaN
34,10bff5ed-c4b5-421e-bbc3-7295bc8603f6,DIMECO,Entreprise,Fabrication de machines-outils pour le travail...,2024,Entre 50 et 99,NaN
35,b8390ad0-ec32-4e93-adfb-6973a710d7ff,ECOTEM,Entreprise,Activité des économistes de la construction,2024,8,non
36,20e9de28-0085-4a24-9d3c-6de7c5b41c1b,AGENCE DE DEVELOPPEMENT ECONOMIQUE D'OCCITANIE,Entreprise,Autres activités de soutien aux entreprises n....,2023,Entre 100 et 199,NaN
37,4894b171-9a70-49d7-be81-3c7c5c8dd3e9,ECOLE NATIONALE VETERINAIRE DE TOULOUSE,Établissement public,Enseignement supérieur,2023,Entre 250 et 499,NaN
38,856315f0-ece3-4253-a6f5-5c7a9cd8017a,ECOLE NATIONALE VETERINAIRE D'ALFORT,Établissement public,Enseignement supérieur,2023,Entre 250 et 499,NaN
39,2f05b0c1-6cf1-4e7e-9666-9624830ab7dc,CAISSE DES ECOLES,Établissement public,Action sociale sans hébergement n.c.a.,2023,20,NaN
40,16a01174-756d-4af2-a94b-4e817aae89b2,Eco CO2,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,NaN
41,4cefcafa-34a0-4451-aa83-d41c9b712067,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,Services du feu et de secours,2023,Entre 2 000 et 4 999,NaN
42,42b82e62-5d1b-4a2a-8286-ba5b2c2f7f9b,Bretagne Telecom,Entreprise,Télécommunications filaires,2023,140,NaN
43,0becf444-b899-4cc6-bdd5-8b73915e4231,ECOLOR,Entreprise,"Ingénierie, études techniques",2023,Entre 10 et 19,NaN
44,26aaca6f-bccf-46b4-90ba-8b245a6a9f4b,DECOADER,Entreprise,Autre imprimerie (labeur),2023,Entre 50 et 99,NaN
45,e1596c55-5c53-45e1-be0e-57a9e567e185,Grenoble Ecole de Management,Entreprise,Enseignement supérieur,2023,Entre 250 et 499,NaN
46,f2176007-26a5-4841-ba7e-0c97a5497626,MEDINGER ENVIRONNEMENT,Entreprise,Travaux de terrassement courants et travaux pr...,2023,Entre 20 et 49,NaN
47,ba2cc98d-b60c-4617-bcad-95a9510b7568,AC ENVIRONNEMENT,Entreprise,"Analyses, essais et inspections techniques",2023,Entre 250 et 499,NaN
48,1e64c3dc-6304-4aa5-8e52-55e7dffb2c49,ECOLE NATIONALE DES PONTS ET CHAUSSEES,Établissement public,Enseignement supérieur,2023,500,NaN
49,08579e95-35a4-4ea2-b6de-02342782695f,ECOLE NATIONALE SUPERIEURE DE LA POLICE,Établissement public,Activités d'ordre public et de sécurité,2023,Entre 250 et 499,NaN

## Extract unique candidate organization names

This query returns unique organization names matching carbon, climate, sustainability, green, eco, or environmental keywords.

The purpose is to identify possible firms before choosing the final three BEGES reports for detailed analysis.

In [40]:
candidate_names = conn.sql("""
SELECT DISTINCT
    "Raison sociale",
    "Type de structure",
    "Libellé"
FROM beges
WHERE UPPER("Raison sociale") LIKE '%CARBONE%'
   OR UPPER("Raison sociale") LIKE '%CLIMAT%'
   OR UPPER("Raison sociale") LIKE '%ENVIRON%'
   OR UPPER("Raison sociale") LIKE '%GREEN%'
   OR UPPER("Raison sociale") LIKE '%ECO%'
   OR UPPER("Raison sociale") LIKE '%DURABLE%'
   OR UPPER("Raison sociale") LIKE '%SUSTAIN%'
ORDER BY "Raison sociale"
""").df()

candidate_names

,Raison sociale,Type de structure,Libellé
0,SOCIETE INSTALLATIONS TELECOMS COURANTS FORTS,Entreprise,Travaux d'installation électrique dans tous lo...
1,AC ENVIRONNEMENT,Entreprise,"Analyses, essais et inspections techniques"
2,AGENCE DE DEVELOPPEMENT ECONOMIQUE D'OCCITANIE,Entreprise,Autres activités de soutien aux entreprises n....
3,AGENCE DE L ENVIRONNEMENT ET DE LA MAITRISE DE...,Établissement public,Administration publique (tutelle) des activité...
4,ALGECO,Entreprise,"Location et location-bail d'autres machines, é..."
5,AQUITAINE VERRE DECOR,Entreprise,Activités spécialisées de design
6,ASSOCIATION ESTP - GRANDE ECOLE D'INGENIEURS D...,Association,Enseignement supérieur
7,All4green,Entreprise,Commerce de gros (commerce interentreprises) a...
8,Artemisia Environnement,Entreprise,Commerce de gros (commerce interentreprises) d...
9,BOUYGUES TELECOM,Entreprise,Télécommunications sans fil
10,BRANGEON ENVIRONNEMENT,Entreprise,Collecte des déchets non dangereux
11,Bretagne Telecom,Entreprise,Télécommunications filaires
12,CABINET LAMY ENVIRONNEMENT,Entreprise,Conseil pour les affaires et autres conseils d...
13,CAISSE DES ECOLES,Établissement public,Action sociale sans hébergement n.c.a.
14,CAISSE DES ECOLES DE SAINT JOSEPH,Établissement public,Action sociale sans hébergement n.c.a.
15,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,"Analyses, essais et inspections techniques"
16,CASSINI ENVIRONNEMENT ARTIFEX,Entreprise,Activités des sièges sociaux
17,CEMENTIS PRECONTRAINT,Entreprise,Fabrication d'éléments en béton pour la constr...
18,CKFD environnement,Entreprise,Collecte des déchets non dangereux
19,CONSTRUCTEL CONSTRUCTIONS TELECOMMUNICA.,Entreprise,Construction de réseaux électriques et de télé...
20,Carbone 4,Entreprise,"Activités spécialisées, scientifiques et techn..."
21,Centre hospitalier de CREVECOEUR-LE-GRAND,Établissement public,Activités hospitalières
22,Climat Local,Entreprise,"Activités spécialisées, scientifiques et techn..."
23,DECOADER,Entreprise,Autre imprimerie (labeur)
24,DECONSTRUCTION SENCE THIERRY,Entreprise,Travaux de démolition
25,DECOR WORLD SERVICES,Entreprise,Activités spécialisées de design
26,DECOREC,Entreprise,Décolletage
27,DECORTES,Entreprise,Fabrication de structures métalliques et de pa...
28,DIFFUSION INTERNATIONALE D'ARTICLES POUR LE DE...,Entreprise,Fabrication d'éléments en matières plastiques ...
29,DIMECO,Entreprise,Fabrication de machines-outils pour le travail...
30,"Direction régionale de l'environnement, de l'a...",État,Administration publique (tutelle) des activité...
31,"Direction régionale de l'environnement, de l'a...",État,NaN
32,Défense Environnement Services,Entreprise,Activités combinées de soutien lié aux bâtiments
33,ECOCERT,Entreprise,"Analyses, essais et inspections techniques"
34,ECOCERT SA,Entreprise,"Analyses, essais et inspections techniques"
35,ECOCOM,Entreprise,Formation continue d'adultes
36,ECOFIX,Entreprise,Commerce de gros (commerce interentreprises) d...
37,ECOLE CENTRALE DE LYON,Établissement public,Enseignement supérieur
38,ECOLE CENTRALE DE NANTES,Établissement public,Enseignement supérieur
39,ECOLE DE CONDE,Entreprise,Enseignement supérieur
40,ECOLE DES HAUTES ETUDES EN SANTE PUBLIQUE,Établissement public,Enseignement supérieur
41,ECOLE DES HAUTES ETUDES EN SCIENCES SOCIALES,Établissement public,Enseignement supérieur
42,ECOLE NATIONALE DE L'AVIATION CIVILE,Établissement public,Enseignement supérieur
43,ECOLE NATIONALE DE LA MAGISTRATURE,Établissement public,Enseignement supérieur
44,ECOLE NATIONALE DES PONTS ET CHAUSSEES,Établissement public,Enseignement supérieur
45,ECOLE NATIONALE SUPERIEURE D'ARCHITECTURE ET D...,Établissement public,Enseignement supérieur
46,ECOLE NATIONALE SUPERIEURE D'ARTS ET METIERS (...,Établissement public,Enseignement supérieur
47,ECOLE NATIONALE SUPERIEURE DE FORMATION DE L'E...,Établissement public,Enseignement supérieur
48,ECOLE NATIONALE SUPERIEURE DE LA POLICE,Établissement public,Activités d'ordre public et de sécurité
49,ECOLE NATIONALE SUPERIEURE DE LA POLICE,Établissement public,"Administration publique (tutelle) de la santé,..."
50,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,Établissement public,Enseignement supérieur
51,ECOLE NATIONALE SUPERIEURE MARITIME,Établissement public,Enseignement supérieur
52,ECOLE NATIONALE SUPÉRIEURE DES MINES DE SAINT-...,Établissement public,Enseignement supérieur
53,ECOLE NATIONALE VETERINAIRE D'ALFORT,Établissement public,Enseignement supérieur
54,ECOLE NATIONALE VETERINAIRE DE TOULOUSE,Établissement public,Enseignement supérieur
55,ECOLE NORMALE SUPERIEURE,Établissement public,Enseignement supérieur
56,ECOLE NORMALE SUPERIEURE DE LYON,Établissement public,Enseignement supérieur
57,ECOLE NORMALE SUPERIEURE DE RENNES,Établissement public,Enseignement supérieur
58,ECOLE POLYTECHNIQUE,Établissement public,Enseignement supérieur
59,ECOLOR,Entreprise,"Ingénierie, études techniques"
60,ECOTEC,Entreprise,Enseignement supérieur
61,ECOTEM,Entreprise,Activité des économistes de la construction
62,EGGER PANNEAUX ET DECORS,Entreprise,Fabrication de placage et de panneaux de bois
63,EIFFAGE ENERGIE SYSTEMES - TELECOM SUD EST,Entreprise,Construction de réseaux électriques et de télé...
64,ENGIE GREEN FRANCE,Entreprise,Conseil pour les affaires et autres conseils d...
65,ENVIRONNEMENT DES RESEAUX,Entreprise,Construction de réseaux pour fluides
66,ENVIRONNEMENT MASSIF CENTRAL,Entreprise,Récupération de déchets triés
67,ETABLISSEMENT PUBLIC PALAIS DE LA DECOUVERTE E...,Établissement public,Gestion des musées
68,Eco CO2,Entreprise,"Activités spécialisées, scientifiques et techn..."
69,Eco-Tech Ceram,Entreprise,"Ingénierie, études techniques"
70,EcoAct SAS,Entreprise,Autres activités de soutien aux entreprises n....
71,Ecocert,Entreprise,"Analyses, essais et inspections techniques"
72,Ecole Nationale Supérieure de Chimie de Paris,Établissement public,Enseignement supérieur
73,Ecole Nationale d'Ingénieurs de Saint-Etienne,Établissement public,Enseignement supérieur
74,Ecole Nationale des Sports de Montagne,Établissement public,Enseignement supérieur
75,Ecole Nationale des Techniciens de l'Equipement,État,NaN
76,Ecologie Urbaine,Entreprise,"Activités spécialisées, scientifiques et techn..."
77,Econocom,Entreprise,Location et location-bail de machines de burea...
78,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn..."
79,Ergi eco,Entreprise,"Ingénierie, études techniques"
80,Everyone Eco,Entreprise,"Activités spécialisées, scientifiques et techn..."
81,FARECO SAS,Entreprise,Fabrication d'autres matériels électriques
82,FINERGREEN,Entreprise,Conseil pour les affaires et autres conseils d...
83,FITECO,Entreprise,Activités comptables
84,FRANCE DECORS SAS,Entreprise,Fabrication de meubles de bureau et de magasin
85,France Ville Durable,Association,Autres organisations fonctionnant par adhésion...
86,GESTECO,Entreprise,Services administratifs combinés de bureau
87,GREEN MOTION SOLUTIONS,Entreprise,Transports de voyageurs par taxis
88,GREEN OUTSIDE,Entreprise,Commerce de gros (commerce interentreprises) n...
89,GROUPE DES ECOLES NATIONALES D ECONOMIE ET STA...,Établissement public,Enseignement supérieur
90,GROUPE SECOB RENNES,Entreprise,Activités comptables
91,GUY DAUPHIN ENVIRONNEMENT,Entreprise,Récupération de déchets triés
92,Grenoble Ecole de Management,Entreprise,Enseignement supérieur
93,Groupe Nicollin Environnement,Entreprise,Activités des sociétés holding
94,Groupe Pizzorno Environnement,Entreprise,Collecte des déchets non dangereux
95,Groupement d’Intérêt Economique ELEGIA,Entreprise,Autre mise à disposition de ressources humaines
96,I4CE INSTITUTE FOR CLIMATE ECONOMICS,Association,Autres organisations fonctionnant par adhésion...
97,INSTITUT ENSEIGNEMENT SUPERIEUR ET RECHERCHE E...,Établissement public,Enseignement supérieur
98,INSTITUT MINES TELECOM,Établissement public,Enseignement supérieur
99,INSTITUT NATIONAL DE L'ENVIRONNEMENT INDUSTRIE...,Établissement public,"Analyses, essais et inspections techniques"
100,INSTITUT NATIONAL DE RECHERCHE POUR L'AGRICULT...,Établissement public,Recherche-développement en autres sciences phy...
101,INSTITUT NATIONAL DES SCIENCES ET INDUSTRIES D...,Établissement public,Enseignement supérieur
102,IVECO FRANCE,Entreprise,Construction de véhicules automobiles
103,L'ECOLE FRANCAISE,Entreprise,Formation continue d'adultes
104,L'INSTITUT AGRO (Institut national d'enseignem...,Établissement public,Enseignement supérieur
105,LATECOERE,Entreprise,Construction aéronautique et spatiale
106,LB ECO HABITAT,Entreprise,Travaux de maçonnerie générale et gros œuvre d...
107,LYRECO FRANCE,Entreprise,Commerce de gros (commerce interentreprises) d...
108,MEDINGER ENVIRONNEMENT,Entreprise,Travaux de terrassement courants et travaux pr...
109,Mecojit,Entreprise,Travaux d'installation électrique dans tous lo...
110,Mosaïque Environnement,Entreprise,"Ingénierie, études techniques"
111,NATURE ET DECOUVERTES SA,Entreprise,Autres commerces de détail spécialisés divers
112,NC 2008 Environnement,Entreprise,Travaux d'isolation
113,NCA environnement,Entreprise,"Ingénierie, études techniques"
114,ORTEC ENVIRONNEMENT,Entreprise,Collecte des déchets non dangereux
115,OUTREMER TELECOM,Entreprise,Télécommunications sans fil
116,PAPETERIES DU COTENTIN (PAPECO) S.A.S.,Entreprise,Fabrication d'articles en papier à usage sanit...
117,PAPILLONS BLANCS DENAIN ET ENVIRONS,Association,Hébergement social pour handicapés mentaux et ...
118,PERFEST ENVIRONNEMENT,Entreprise,Commerce de gros (commerce interentreprises) d...
119,Polyexpert environnement,Entreprise,"Analyses, essais et inspections techniques"
120,Premier Tech Eau et Environnement,Entreprise,Fabrication d'éléments en matières plastiques ...
121,RAMERY ENVIRONNEMENT,Entreprise,Collecte des déchets non dangereux
122,RECORD PORTES AUTOMATIQUES,Entreprise,Fabrication de portes et fenêtres en métal
123,RHON'TELECOM,Entreprise,"Ingénierie, études techniques"
124,RHÔN'TELECOM SAS,Entreprise,"Ingénierie, études techniques"
125,SAS ECOLE SUPERIEURE DE COMMERCE ET COMMUNICAT...,Entreprise,Enseignement supérieur
126,SAS OBJECTIF ZERO CARBONE CONSULTING (CARBONO),Entreprise,"Activités spécialisées, scientifiques et techn..."
127,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,Services du feu et de secours
128,SCE DEPARTEMENTAL INCENDIE ET SECOURS,Établissement public,"Administration publique (tutelle) de la santé,..."
129,SCE DEPARTEMENTAL INCENDIE ET SECOURS DE LA SA...,Établissement public,Services du feu et de secours
130,SCE DEPARTEMENTAL INCENDIE ET SECOURS DU TARN,Établissement public,Services du feu et de secours
131,SCOP EcoZimut,Entreprise,"Ingénierie, études techniques"
132,SECHE ENVIRONNEMENT,Entreprise,Activités des sièges sociaux
133,SECOGES,Entreprise,Activités comptables
134,SERVICE DEPARTEMENTAL D'INCENDIE ET DE SECOURS,Établissement public,Services du feu et de secours
135,SERVICE DEPARTEMENTAL D'INCENDIE ET DE SECOURS...,Établissement public,Services du feu et de secours
136,SERVICE DEPARTEMENTAL D'INCENDIE ET DE SECOURS...,Établissement public,Services du feu et de secours
137,SERVICE DEPARTEMENTAL-METROPOLITAIN D'INCENDIE...,Établissement public,Services du feu et de secours
138,SERVICE INCENDIE ET SECOURS DU HAUT-RHIN,Établissement public,Services du feu et de secours
139,SFECO SOLUTIONS,Entreprise,Construction de réseaux électriques et de télé...
140,SNEF Telecom,Entreprise,Travaux d'installation électrique dans tous lo...
141,SOCIETE D'ECONOMIE MIXTE DES TRANSPORTS,Entreprise,Transports urbains et suburbains de voyageurs
142,STAND EXPO DECO,Entreprise,Agencement de lieux de vente
143,STE D'ECONOMIE MIXTE DES TRANSPORTS EN COMMUN ...,Entreprise,Transports urbains et suburbains de voyageurs
144,STECO,Entreprise,Activités comptables
145,Secours Catholique - Caritas France,Association,Action sociale sans hébergement n.c.a.
146,Secrétariat Général des Ministères Economiques...,État,Administration publique générale
147,Sphereco SAS,Entreprise,Autres commerces de détail en magasin non spéc...
148,TECHNI DECO S.A,Entreprise,Décolletage
149,TEXDECOR SAS,Entreprise,Commerce de gros (commerce interentreprises) d...
150,THEOGAM concept deco,Entreprise,Location de terrains et d'autres biens immobil...
151,UNION DE RECOUVREMENT DE SECURITE SOCIALE ET D...,Entreprise,Activités générales de sécurité sociale
152,UNION POUR LE RECOUVREMENT DES COTISATIONS DE ...,Entreprise,Activités générales de sécurité sociale
153,URBASER ENVIRONNEMENT,Entreprise,Collecte des déchets non dangereux
154,VEOLIA ENVIRONNEMENT,Entreprise,Autres activités de soutien aux entreprises n....
155,Wagner Environnement Travaux Publics (WETP),Entreprise,Travaux de terrassement courants et travaux pr...
156,Wisecom,Entreprise,Activités des agences de publicité
157,sas therond decoration,Entreprise,Commerce de gros (commerce interentreprises) d...

In [41]:
structured_candidates = conn.sql("""
SELECT
    "Id",
    "Raison sociale",
    "Type de structure",
    "APE(NAF) associé",
    "Libellé",
    "Année de reporting",
    "Assujetti à la CSRD",
    "Nombre de salariés/d'agents de l'ensemble des SIREN déclarés sur ce bilan lors de l'année de reporting du bilan" AS staff_count,
    "Mode de consolidation",
    "Emissions publication P1.1",
    "Emissions publication P2.1",
    "Emissions publication P3.1",
    "Emissions publication P3.2",
    "Emissions publication P3.3",
    "Emissions publication P4.1",
    "Emissions publication P4.2",
    "Emissions publication P5.1",
    "Actions et moyens",
    "Objectif de réduction pour 2030",
    "Lien URL vers le rapport complet du BEGES"
FROM beges
WHERE "Année de reporting" >= 2022
  AND (
      UPPER("Libellé") LIKE '%CONSEIL%'
      OR UPPER("Libellé") LIKE '%INGÉNIERIE%'
      OR UPPER("Libellé") LIKE '%INGENIERIE%'
      OR UPPER("Libellé") LIKE '%ÉTUDES%'
      OR UPPER("Libellé") LIKE '%ETUDES%'
      OR UPPER("Libellé") LIKE '%ENVIRONNEMENT%'
      OR UPPER("Libellé") LIKE '%TECHNIQUE%'
  )
ORDER BY "Année de reporting" DESC, staff_count DESC
""").df()

structured_candidates.shape

(573, 20)

## Inspect activity labels in the structured candidate pool

This query groups the candidate pool by activity label.

The goal is to identify which NAF activity categories are actually present in the filtered dataset, so the final firm selection can be based on relevant business activities rather than company-name guessing.

In [42]:
conn.register("structured_candidates", structured_candidates)

conn.sql("""
SELECT
    "Libellé",
    COUNT(*) AS number_of_reports
FROM structured_candidates
GROUP BY "Libellé"
ORDER BY number_of_reports DESC
""").df()

                                              Libellé  number_of_reports
0                       Ingénierie, études techniques                183
1      Conseil en systèmes et logiciels informatiques                147
2   Conseil pour les affaires et autres conseils d...                119
3   Activités spécialisées, scientifiques et techn...                 27
4   Fabrication de pièces techniques à base de mat...                 24
5          Analyses, essais et inspections techniques                 22
6   Fabrication d'instrumentation scientifique et ...                 19
7                        Études de marché et sondages                 12
8     Conseil en relations publiques et communication                  7
9   Fabrication d'autres textiles techniques et in...                  6
10  Enseignement secondaire technique ou professio...                  5
11                      Contrôle technique automobile                  1
12  Fabrication et façonnage d'autres articles en ...                  1

## Filter to relevant consultancy and technical advisory activities

This block narrows the candidate pool to activity labels that fit the project scope: engineering studies, management or sustainability consulting, and technical analysis or inspection.

These categories are more relevant for comparing environmental, sustainability, carbon, and technical advisory organizations than unrelated manufacturing or education activities.

In [43]:
relevant_candidates = conn.sql("""
SELECT *
FROM structured_candidates
WHERE "Libellé" IN (
    'Ingénierie, études techniques',
    'Conseil pour les affaires et autres conseils de gestion',
    'Analyses, essais et inspections techniques',
    'Activités spécialisées, scientifiques et techniques diverses'
)
ORDER BY "Année de reporting" DESC, staff_count DESC
""").df()

relevant_candidates.shape

(351, 20)

## Rank candidates by Scope 3 reporting depth

This block estimates Scope 3 reporting depth by summing the available indirect emissions publication columns.

For this project, firms with visible indirect emissions are more useful because the analysis focuses on Scope 3 coverage, reporting completeness, and alignment with modern climate disclosure expectations.

In [44]:
ranked_candidates = conn.sql("""
SELECT
    "Id",
    "Raison sociale",
    "Type de structure",
    "Libellé",
    "Année de reporting",
    staff_count,
    "Assujetti à la CSRD",
    "Mode de consolidation",
    (
        COALESCE("Emissions publication P3.1", 0) +
        COALESCE("Emissions publication P3.2", 0) +
        COALESCE("Emissions publication P3.3", 0) +
        COALESCE("Emissions publication P4.1", 0) +
        COALESCE("Emissions publication P4.2", 0) +
        COALESCE("Emissions publication P5.1", 0)
    ) AS visible_indirect_emissions,
    "Actions et moyens",
    "Objectif de réduction pour 2030",
    "Lien URL vers le rapport complet du BEGES"
FROM relevant_candidates
ORDER BY 
    "Année de reporting" DESC,
    visible_indirect_emissions DESC
""").df()

ranked_candidates.head(30)

,Id,Raison sociale,Type de structure,Libellé,Année de reporting,staff_count,Assujetti à la CSRD,Mode de consolidation,visible_indirect_emissions,Actions et moyens,Objectif de réduction pour 2030,Lien URL vers le rapport complet du BEGES
0,40a6ae82-78e0-42f3-ac7e-d92f6df13857,NXO FRANCE,Entreprise,"Ingénierie, études techniques",2025,1196,non,Opérationnel,8.280800e+04,Principales actions de décarbonation prévues s...,NaN,NaN
1,3bedd9e7-4de6-4a0c-9d51-dcaef764f1bf,SAFEGE,Entreprise,"Ingénierie, études techniques",2025,817,non,Opérationnel,2.789021e+03,Déplacements:Adaptation des modes de déplaceme...,-20% vs 2024: soit une réduction de 1007 tCO2e...,NaN
2,fb193005-867d-424c-971d-e78a983d2024,AGENCE FRANCAISE D'EXPERTISE TECHNIQUE INTERNA...,Établissement public,"Activités spécialisées, scientifiques et techn...",2025,2475,NaN,Opérationnel,1.813670e+03,Le Bilan Carbone de 2025 représente l&#039;ann...,NaN,NaN
3,aa321581-bde7-485f-bfc5-cb96647f8a0a,CIRTES SRC,Entreprise,"Activités spécialisées, scientifiques et techn...",2025,21,non,Opérationnel,4.811882e+02,Sortir certains produits du stock et rénover é...,Améliorer la performance énergétique des bâtim...,NaN
4,e75952c3-75c9-4182-b03e-fda04c203f05,Sol Solution,Entreprise,"Ingénierie, études techniques",2025,90,non,Opérationnel,4.223000e+02,SOL SOLUTION a engagé une démarche structurée ...,-40% par rapport à notre année de référence 2023,La Méthode Bilan Carbone® de l'ADEME
5,3c5d011c-5cd0-42b3-80e9-b73c062b067a,Humans Matter,Entreprise,Conseil pour les affaires et autres conseils d...,2025,61,NaN,Opérationnel,8.740000e+01,Humans Matter a identifié plusieurs actions pr...,Oui → réduction alignée SBTi :\nScope 1 & 2 : ...,NaN
6,ab5287c5-895a-44e9-aac7-035a4c3ec015,AQUASSAY,Entreprise,"Ingénierie, études techniques",2025,24,non,Opérationnel,7.500000e+01,NaN,12%,NaN
7,174bf12e-6f86-4aa4-a38f-fbd140a2ea10,INGENERIA,Entreprise,Conseil pour les affaires et autres conseils d...,2025,4,non,Opérationnel,5.000000e+01,Mobilisation des prestataires Préparation et ...,-20%,NaN
8,c9beb36d-1ea7-4c0a-aeca-f142890fd434,TASMANE,Entreprise,Conseil pour les affaires et autres conseils d...,2025,63,non,Opérationnel,4.100000e+01,Les actions de réduction identifiées s’articul...,Tasmane se fixe un objectif de réduction progr...,NaN
9,19541c22-bfe0-4e46-84b1-f1a70eae3f98,Conseil Formation Méditerranée,Entreprise,Conseil pour les affaires et autres conseils d...,2025,11,non,Opérationnel,1.601000e+01,RAS,NaN,NaN
10,4d2b1f96-ca35-4c4b-93c9-f33f45933363,Ekho,Entreprise,Conseil pour les affaires et autres conseils d...,2025,6,non,Opérationnel,2.480000e+00,4 axes d&#039;actions :1 - Intrants services ...,NaN,https://ekho.green
11,955319b3-c86f-409e-a08e-edee82d0c168,Maltese Technologies,Entreprise,Conseil pour les affaires et autres conseils d...,2025,5,non,Opérationnel,1.940000e+00,Amélioration de l’efficacité énergétique de l’...,"-30% vs 2025 soit -1,63 tCO₂e",NaN
12,99701085-719f-4af4-a87c-484655912910,VULCAIN SERVICES,Entreprise,"Ingénierie, études techniques",2024,1411,NaN,Opérationnel,1.186202e+06,NaN,Diminution des émissions de gaz à effet de ser...,NaN
13,1d9acfee-ef13-4fdd-971f-245bde451611,Clariane,Entreprise,Conseil pour les affaires et autres conseils d...,2024,63086,NaN,Opérationnel,4.425260e+05,"En termes de réduction d’impact, le Groupe s’e...","-25% des émissions GES totales (scopes 1, 2, 3)","Publication au sein de l'URD 2024 du Groupe, e..."
14,6f58967d-5957-402c-ab93-298ad07d391e,PRODEVAL,Entreprise,"Ingénierie, études techniques",2024,380,NaN,Opérationnel,1.267470e+05,Plan de mobilité interneConception de produit ...,NaN,https://prodeval.aktio.cc/public_reports/1756
15,1e25a862-88b4-41c3-b108-6c642b4d57bd,CAP INGELEC,Entreprise,"Ingénierie, études techniques",2024,650,non,Opérationnel,1.093130e+05,CAP INGELEC entame en 2026 la démarche ACT Pas...,NaN,NaN
16,4f00070e-408e-4a86-a519-59c1bb6be503,EPSA,Entreprise,Conseil pour les affaires et autres conseils d...,2024,2274,NaN,Opérationnel,2.672400e+04,EPSA a construit une stratégie climat en s&#03...,"-52% d'émissions de carbone sur les scopes 1, ...",NaN
17,bec838cf-4796-4624-b73e-248c2855784a,BERTIN TECHNOLOGIES,Entreprise,"Ingénierie, études techniques",2024,1000,oui,Opérationnel,1.395400e+04,Achats :Challenger les fournisseursPlus grande...,NaN,NaN
18,0fa9857c-9f77-497c-89af-0727a0bca8b9,LABOCEA,Établissement public,"Analyses, essais et inspections techniques",2024,609,NaN,Opérationnel,9.956000e+03,En cours,NaN,NaN
19,00246a9c-0d50-42c5-9bc5-71a82f16065b,DERICHEBOURG AERONAUTICS SERVICES FRANCE,Entreprise,"Ingénierie, études techniques",2024,1422,NaN,Opérationnel,9.136670e+03,1,-25%,https://www.eliorgroup.com/sites/www.eliorgrou...
20,267a82fd-d963-4cc7-b0ef-4e2ac0859f52,MOONGY,Entreprise,"Ingénierie, études techniques",2024,2887,NaN,Opérationnel,7.990900e+03,-Promouvoir les modes de déplacement durable-P...,Réduire l'intensité carbone économique de 30% ...,NaN
21,95a9d2c8-2be5-4d42-a5c0-4950a2a57ce8,SCOP EcoZimut,Entreprise,"Ingénierie, études techniques",2024,16,NaN,Opérationnel,6.915000e+03,"Projets et usagesLâcher les gaz, pour plus de ...",NaN,NaN
22,5241ed0c-c2af-49b1-9744-d78d31a4190d,EXCENT FRANCE,Entreprise,"Ingénierie, études techniques",2024,652,NaN,Opérationnel,6.859380e+03,"Emissions produit : Ecoconception, achats resp...",Notre objectif 2030 est d'avoir un bilan carbo...,NaN
23,7a0b6f91-9d03-4851-a2cc-9f2ab53b21d5,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,"Analyses, essais et inspections techniques",2024,890,NaN,Opérationnel,6.453000e+03,Le groupe CARSO investit pour réduire ses émis...,42% de réduction des émissions,NaN
24,b646e185-9c12-4d62-9dc3-5500792bdce7,DEVOTEAM,Entreprise,"Ingénierie, études techniques",2024,10171,NaN,Opérationnel,5.804120e+03,Pour mener à bien nos objectifs de décarbonat...,"Scope 1 & 2 : - 33,3 %\nScope 3 : - 44 %",https://devo.team/sustainability-report-2024
25,9162d468-d9df-47f8-a158-d216193b0f72,ENERFLUX,Entreprise,"Ingénierie, études techniques",2024,180,NaN,Opérationnel,5.092000e+03,-,L'objectif est de réduire notre empreinte carb...,NaN
26,7abf0530-3f2c-46e1-8386-497989ef799c,SOCOTEC,Entreprise,"Analyses, essais et inspections techniques",2024,6075,oui,Opérationnel,4.090870e+03,"Depuis 2022, SOCOTEC mets en œuvre un plan d’a...",42% de réduction sur le scope 1 et 2,NaN
27,ade0303e-aef1-44e4-8e22-d9901eeee04b,Ingerop,Entreprise,"Ingénierie, études techniques",2024,3500,NaN,Opérationnel,3.985420e+03,Des actions d&#039;allongement de la durée de ...,NaN,NaN
28,4103d7f9-088c-4a42-8da0-216b5d758007,REDBRIDGE FRANCE SAS,Entreprise,Conseil pour les affaires et autres conseils d...,2024,47,NaN,Opérationnel,3.642000e+03,"Dans un premier temps, nous souhaitons sensibi...","Objectif de réduction de -7,1% d'émissions / an",NaN
29,4b7a4186-d0ef-4e85-95f7-059cf725ca2b,INSTITUT TECHNIQUE GAZ ET AIR,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,805,oui,Opérationnel,3.512000e+03,Plan d’actions- Plan de mobilité déplacement d...,42% de réduction,NaN

## Search for named sustainability, carbon, and environmental advisory firms

This block searches the candidate pool for organizations that are likely to be directly relevant to the project theme.

At this stage, the goal is not to rank by emissions volume. The goal is to identify firms whose business activity makes them interesting subjects for a meta-analysis of GHG reporting quality.

In [45]:
target_firms = conn.sql("""
SELECT
    "Id",
    "Raison sociale",
    "Type de structure",
    "Libellé",
    "Année de reporting",
    staff_count,
    "Assujetti à la CSRD",
    "Mode de consolidation",
    visible_indirect_emissions,
    "Actions et moyens",
    "Objectif de réduction pour 2030",
    "Lien URL vers le rapport complet du BEGES"
FROM ranked_candidates
WHERE UPPER("Raison sociale") LIKE '%CARBONE%'
   OR UPPER("Raison sociale") LIKE '%GREEN%'
   OR UPPER("Raison sociale") LIKE '%ECO%'
   OR UPPER("Raison sociale") LIKE '%CLIMAT%'
   OR UPPER("Raison sociale") LIKE '%ENVIRON%'
   OR UPPER("Raison sociale") LIKE '%SUSTAIN%'
   OR UPPER("Raison sociale") LIKE '%I CARE%'
   OR UPPER("Raison sociale") LIKE '%EKODEV%'
   OR UPPER("Raison sociale") LIKE '%UTOPIES%'
   OR UPPER("Raison sociale") LIKE '%ECOACT%'
   OR UPPER("Raison sociale") LIKE '%GREENFLEX%'
   OR UPPER("Raison sociale") LIKE '%ARTELIA%'
   OR UPPER("Raison sociale") LIKE '%EGIS%'
   OR UPPER("Raison sociale") LIKE '%SETEC%'
   OR UPPER("Raison sociale") LIKE '%ANTEA%'
   OR UPPER("Raison sociale") LIKE '%SOCOTEC%'
ORDER BY "Année de reporting" DESC, visible_indirect_emissions DESC
""").df()

target_firms

,Id,Raison sociale,Type de structure,Libellé,Année de reporting,staff_count,Assujetti à la CSRD,Mode de consolidation,visible_indirect_emissions,Actions et moyens,Objectif de réduction pour 2030,Lien URL vers le rapport complet du BEGES
0,95a9d2c8-2be5-4d42-a5c0-4950a2a57ce8,SCOP EcoZimut,Entreprise,"Ingénierie, études techniques",2024,16,NaN,Opérationnel,6915.00,"Projets et usagesLâcher les gaz, pour plus de ...",NaN,NaN
1,7a0b6f91-9d03-4851-a2cc-9f2ab53b21d5,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,"Analyses, essais et inspections techniques",2024,890,NaN,Opérationnel,6453.00,Le groupe CARSO investit pour réduire ses émis...,42% de réduction des émissions,NaN
2,7abf0530-3f2c-46e1-8386-497989ef799c,SOCOTEC,Entreprise,"Analyses, essais et inspections techniques",2024,6075,oui,Opérationnel,4090.87,"Depuis 2022, SOCOTEC mets en œuvre un plan d’a...",42% de réduction sur le scope 1 et 2,NaN
3,d70a0f1c-b69c-4600-994b-80d1c903b8b5,ECOCERT SA,Entreprise,"Analyses, essais et inspections techniques",2024,778,NaN,Opérationnel,1242.70,La gouvernance a été renforcée avec l’évolutio...,NaN,NaN
4,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non,Opérationnel,392.24,Limitation de la vitesse sur autoroute à 110 k...,Réduction de 100tCO2e,NaN
5,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non,Opérationnel,392.24,Limitation de la vitesse sur autoroute à 110 k...,Réduction de 100tCO2e,NaN
6,5e1dcbd9-1848-4e05-a510-ef28436ed9ea,SAS OBJECTIF ZERO CARBONE CONSULTING (CARBONO),Entreprise,"Activités spécialisées, scientifiques et techn...",2024,6,NaN,Opérationnel,9.08,Remplacer nos véhicules diesel par des véhicul...,NaN,NaN
7,383f4915-42c7-4be6-a174-e996ccb2d761,ANTEA FRANCE,Entreprise,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,NaN,Opérationnel,3179.10,Plan d&#039;actions en cours de validation ( R...,NaN,https://www.anteagroup.fr/uploads/media/file/1...
8,ba2cc98d-b60c-4617-bcad-95a9510b7568,AC ENVIRONNEMENT,Entreprise,"Analyses, essais et inspections techniques",2023,Entre 250 et 499,NaN,Opérationnel,2624.00,Etudier les entreprises de services sous-trait...,NaN,NaN
9,16a01174-756d-4af2-a94b-4e817aae89b2,Eco CO2,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,NaN,Opérationnel,1447.73,LibelléVolume de réductionIndicateurMoyen / Ob...,-18% des émissions à périmètre constant,NaN
10,0becf444-b899-4cc6-bdd5-8b73915e4231,ECOLOR,Entreprise,"Ingénierie, études techniques",2023,Entre 10 et 19,NaN,Opérationnel,53.00,PILOTAGE Tenir à jour son Bilan Carbone tous l...,Notre objectif de réduction est de - 25 % pour...,NaN
11,cce1f2e1-40a8-4a06-a97a-1f94b392115f,Everyone Eco,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 1 et 2,NaN,Opérationnel,0.54,Everyone Eco souhaite réduire ses émissions de...,"Réduction des émissions de 3,2% par an",NaN
12,61c148dc-e5f2-4309-a019-06daee6079a6,Climat Local,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 3 et 5,NaN,Opérationnel,0.14,Mesurer les déplacements visiteursCovoiturer a...,NaN,https://docs.google.com/spreadsheets/d/1AhuU9G...
13,b09970de-a5b6-4749-a083-8d7b1d6b8cff,ENGIE GREEN FRANCE,Entreprise,Conseil pour les affaires et autres conseils d...,2022,635,non,Opérationnel,50719.00,Composants éoliens et PV​Augmenter la durée de...,NaN,NaN
14,160374fb-92ed-4227-ad2d-e5e0b6d60cc2,ARTELIA,Entreprise,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,NaN,Opérationnel,12938.00,MOBILITÉLes déplacements constituent notre pre...,Conformément à notre engagement auprès de l'in...,NaN
15,f0e34d33-6a38-4aeb-a538-e1eddf7783bf,INSTITUT NATIONAL DE L'ENVIRONNEMENT INDUSTRIE...,Établissement public,"Analyses, essais et inspections techniques",2022,Entre 500 et 999,NaN,Opérationnel,4781.00,1 - Etude de la mise en service d’une installa...,NaN,NaN
16,80308231-dd72-4b9f-bbbd-e04943f5b97f,Ecocert,Entreprise,"Analyses, essais et inspections techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,2517.60,Scope 1Nous voulons diminuer l&#039;empreinte ...,NaN,Méthodologie BEGES v5
17,08887987-6c61-474a-88a3-3f8ef9a15f05,NCA environnement,Entreprise,"Ingénierie, études techniques",2022,Entre 50 et 99,NaN,Opérationnel,447.00,Le plan de transition de NCA environnement s&#...,NaN,https://nca.fr/rse/
18,0369acaf-e747-4923-9dbd-26ab3bcdf10b,Eco-Tech Ceram,Entreprise,"Ingénierie, études techniques",2022,Entre 20 et 49,NaN,Opérationnel,236.02,Premier jet du plan d&#039;action (en cours d&...,NaN,NaN
19,ad149348-0c48-4852-9489-9a656efbed54,FINERGREEN,Entreprise,Conseil pour les affaires et autres conseils d...,2022,Entre 50 et 99,NaN,Financier,62.00,Incitation à la mobilité douce avec la mise en...,NaN,NaN
20,ad814478-9d04-4cec-8adb-c728ce9ac44b,Ergi eco,Entreprise,"Ingénierie, études techniques",2022,Entre 1 et 2,NaN,Opérationnel,19.00,L’émission de GES est au cœur des réflexions d...,NaN,NaN
21,529a6ede-04ca-4012-86f8-c377f8ab3e12,CABINET LAMY ENVIRONNEMENT,Entreprise,Conseil pour les affaires et autres conseils d...,2022,Entre 3 et 5,NaN,Opérationnel,1.10,Compte-tenu du très faible bilan de nos émissi...,NaN,https://lamy-environnement.com/wp-content/uplo...
22,9c988574-5b55-47a0-b9c1-021fafccbbf9,RHON'TELECOM,Entreprise,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,0.00,Emissions directes Analyse pour changement des...,NaN,NaN
23,a02088c4-1688-45f5-bf1e-77fe1c1b337d,RHÔN'TELECOM SAS,Entreprise,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,0.00,Emissions directes Analyse pour changement de...,NaN,NaN

In [46]:
target_firms.head(30)

,Id,Raison sociale,Type de structure,Libellé,Année de reporting,staff_count,Assujetti à la CSRD,Mode de consolidation,visible_indirect_emissions,Actions et moyens,Objectif de réduction pour 2030,Lien URL vers le rapport complet du BEGES
0,95a9d2c8-2be5-4d42-a5c0-4950a2a57ce8,SCOP EcoZimut,Entreprise,"Ingénierie, études techniques",2024,16,NaN,Opérationnel,6915.00,"Projets et usagesLâcher les gaz, pour plus de ...",NaN,NaN
1,7a0b6f91-9d03-4851-a2cc-9f2ab53b21d5,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,"Analyses, essais et inspections techniques",2024,890,NaN,Opérationnel,6453.00,Le groupe CARSO investit pour réduire ses émis...,42% de réduction des émissions,NaN
2,7abf0530-3f2c-46e1-8386-497989ef799c,SOCOTEC,Entreprise,"Analyses, essais et inspections techniques",2024,6075,oui,Opérationnel,4090.87,"Depuis 2022, SOCOTEC mets en œuvre un plan d’a...",42% de réduction sur le scope 1 et 2,NaN
3,d70a0f1c-b69c-4600-994b-80d1c903b8b5,ECOCERT SA,Entreprise,"Analyses, essais et inspections techniques",2024,778,NaN,Opérationnel,1242.70,La gouvernance a été renforcée avec l’évolutio...,NaN,NaN
4,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non,Opérationnel,392.24,Limitation de la vitesse sur autoroute à 110 k...,Réduction de 100tCO2e,NaN
5,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non,Opérationnel,392.24,Limitation de la vitesse sur autoroute à 110 k...,Réduction de 100tCO2e,NaN
6,5e1dcbd9-1848-4e05-a510-ef28436ed9ea,SAS OBJECTIF ZERO CARBONE CONSULTING (CARBONO),Entreprise,"Activités spécialisées, scientifiques et techn...",2024,6,NaN,Opérationnel,9.08,Remplacer nos véhicules diesel par des véhicul...,NaN,NaN
7,383f4915-42c7-4be6-a174-e996ccb2d761,ANTEA FRANCE,Entreprise,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,NaN,Opérationnel,3179.10,Plan d&#039;actions en cours de validation ( R...,NaN,https://www.anteagroup.fr/uploads/media/file/1...
8,ba2cc98d-b60c-4617-bcad-95a9510b7568,AC ENVIRONNEMENT,Entreprise,"Analyses, essais et inspections techniques",2023,Entre 250 et 499,NaN,Opérationnel,2624.00,Etudier les entreprises de services sous-trait...,NaN,NaN
9,16a01174-756d-4af2-a94b-4e817aae89b2,Eco CO2,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,NaN,Opérationnel,1447.73,LibelléVolume de réductionIndicateurMoyen / Ob...,-18% des émissions à périmètre constant,NaN
10,0becf444-b899-4cc6-bdd5-8b73915e4231,ECOLOR,Entreprise,"Ingénierie, études techniques",2023,Entre 10 et 19,NaN,Opérationnel,53.00,PILOTAGE Tenir à jour son Bilan Carbone tous l...,Notre objectif de réduction est de - 25 % pour...,NaN
11,cce1f2e1-40a8-4a06-a97a-1f94b392115f,Everyone Eco,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 1 et 2,NaN,Opérationnel,0.54,Everyone Eco souhaite réduire ses émissions de...,"Réduction des émissions de 3,2% par an",NaN
12,61c148dc-e5f2-4309-a019-06daee6079a6,Climat Local,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 3 et 5,NaN,Opérationnel,0.14,Mesurer les déplacements visiteursCovoiturer a...,NaN,https://docs.google.com/spreadsheets/d/1AhuU9G...
13,b09970de-a5b6-4749-a083-8d7b1d6b8cff,ENGIE GREEN FRANCE,Entreprise,Conseil pour les affaires et autres conseils d...,2022,635,non,Opérationnel,50719.00,Composants éoliens et PV​Augmenter la durée de...,NaN,NaN
14,160374fb-92ed-4227-ad2d-e5e0b6d60cc2,ARTELIA,Entreprise,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,NaN,Opérationnel,12938.00,MOBILITÉLes déplacements constituent notre pre...,Conformément à notre engagement auprès de l'in...,NaN
15,f0e34d33-6a38-4aeb-a538-e1eddf7783bf,INSTITUT NATIONAL DE L'ENVIRONNEMENT INDUSTRIE...,Établissement public,"Analyses, essais et inspections techniques",2022,Entre 500 et 999,NaN,Opérationnel,4781.00,1 - Etude de la mise en service d’une installa...,NaN,NaN
16,80308231-dd72-4b9f-bbbd-e04943f5b97f,Ecocert,Entreprise,"Analyses, essais et inspections techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,2517.60,Scope 1Nous voulons diminuer l&#039;empreinte ...,NaN,Méthodologie BEGES v5
17,08887987-6c61-474a-88a3-3f8ef9a15f05,NCA environnement,Entreprise,"Ingénierie, études techniques",2022,Entre 50 et 99,NaN,Opérationnel,447.00,Le plan de transition de NCA environnement s&#...,NaN,https://nca.fr/rse/
18,0369acaf-e747-4923-9dbd-26ab3bcdf10b,Eco-Tech Ceram,Entreprise,"Ingénierie, études techniques",2022,Entre 20 et 49,NaN,Opérationnel,236.02,Premier jet du plan d&#039;action (en cours d&...,NaN,NaN
19,ad149348-0c48-4852-9489-9a656efbed54,FINERGREEN,Entreprise,Conseil pour les affaires et autres conseils d...,2022,Entre 50 et 99,NaN,Financier,62.00,Incitation à la mobilité douce avec la mise en...,NaN,NaN
20,ad814478-9d04-4cec-8adb-c728ce9ac44b,Ergi eco,Entreprise,"Ingénierie, études techniques",2022,Entre 1 et 2,NaN,Opérationnel,19.00,L’émission de GES est au cœur des réflexions d...,NaN,NaN
21,529a6ede-04ca-4012-86f8-c377f8ab3e12,CABINET LAMY ENVIRONNEMENT,Entreprise,Conseil pour les affaires et autres conseils d...,2022,Entre 3 et 5,NaN,Opérationnel,1.10,Compte-tenu du très faible bilan de nos émissi...,NaN,https://lamy-environnement.com/wp-content/uplo...
22,9c988574-5b55-47a0-b9c1-021fafccbbf9,RHON'TELECOM,Entreprise,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,0.00,Emissions directes Analyse pour changement des...,NaN,NaN
23,a02088c4-1688-45f5-bf1e-77fe1c1b337d,RHÔN'TELECOM SAS,Entreprise,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,0.00,Emissions directes Analyse pour changement de...,NaN,NaN

## Inspect serious candidate firms

This block isolates the most relevant organizations from the first candidate search.

The goal is to compare firms that are large enough to have meaningful BEGES reporting, active in environmental or technical advisory fields, and likely to provide enough Scope 3 and action-plan information for downstream analysis.

In [48]:
serious_candidates = conn.sql("""
SELECT *
FROM target_firms
WHERE "Raison sociale" IN (
    'SOCOTEC',
    'ECOCERT SA',
    'Ecocert',
    'ANTEA FRANCE',
    'ARTELIA',
    'Eco CO2',
    'Envol Environnement'
)
ORDER BY "Raison sociale", "Année de reporting" DESC
""").df()

serious_candidates

,Id,Raison sociale,Type de structure,Libellé,Année de reporting,staff_count,Assujetti à la CSRD,Mode de consolidation,visible_indirect_emissions,Actions et moyens,Objectif de réduction pour 2030,Lien URL vers le rapport complet du BEGES
0,383f4915-42c7-4be6-a174-e996ccb2d761,ANTEA FRANCE,Entreprise,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,NaN,Opérationnel,3179.10,Plan d&#039;actions en cours de validation ( R...,NaN,https://www.anteagroup.fr/uploads/media/file/1...
1,160374fb-92ed-4227-ad2d-e5e0b6d60cc2,ARTELIA,Entreprise,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,NaN,Opérationnel,12938.00,MOBILITÉLes déplacements constituent notre pre...,Conformément à notre engagement auprès de l'in...,NaN
2,d70a0f1c-b69c-4600-994b-80d1c903b8b5,ECOCERT SA,Entreprise,"Analyses, essais et inspections techniques",2024,778,NaN,Opérationnel,1242.70,La gouvernance a été renforcée avec l’évolutio...,NaN,NaN
3,16a01174-756d-4af2-a94b-4e817aae89b2,Eco CO2,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,NaN,Opérationnel,1447.73,LibelléVolume de réductionIndicateurMoyen / Ob...,-18% des émissions à périmètre constant,NaN
4,80308231-dd72-4b9f-bbbd-e04943f5b97f,Ecocert,Entreprise,"Analyses, essais et inspections techniques",2022,Entre 1 000 et 1 999,NaN,Opérationnel,2517.60,Scope 1Nous voulons diminuer l&#039;empreinte ...,NaN,Méthodologie BEGES v5
5,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non,Opérationnel,392.24,Limitation de la vitesse sur autoroute à 110 k...,Réduction de 100tCO2e,NaN
6,63a4ef27-68c7-41bc-96cd-969faa5d140e,Envol Environnement,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,100,non,Opérationnel,392.24,Limitation de la vitesse sur autoroute à 110 k...,Réduction de 100tCO2e,NaN

## Score candidate reports by data completeness

This block creates a reporting-quality score for candidate organizations.

The goal is to identify BEGES reports that are useful for a comparative analysis. Firms are scored based on whether they report indirect emissions, provide action-plan text, include reduction objectives, discuss uncertainty, list emission factors, and provide sources.

This avoids choosing firms based only on company name and makes the selection process more reproducible.

In [50]:
quality_candidates = conn.sql("""
SELECT
    "Id",
    "Raison sociale",
    "Type de structure",
    "APE(NAF) associé",
    "Libellé",
    "Année de reporting",
    "Nombre de salariés/d'agents de l'ensemble des SIREN déclarés sur ce bilan lors de l'année de reporting du bilan" AS staff_count,
    "Mode de consolidation",

    (
        COALESCE("Emissions publication P3.1", 0) +
        COALESCE("Emissions publication P3.2", 0) +
        COALESCE("Emissions publication P3.3", 0) +
        COALESCE("Emissions publication P4.1", 0) +
        COALESCE("Emissions publication P4.2", 0) +
        COALESCE("Emissions publication P5.1", 0)
    ) AS visible_indirect_emissions,

    CASE WHEN "Actions et moyens" IS NOT NULL AND LENGTH("Actions et moyens") > 20 THEN 1 ELSE 0 END AS has_action_plan,
    CASE WHEN "Objectif de réduction pour 2030" IS NOT NULL AND LENGTH("Objectif de réduction pour 2030") > 5 THEN 1 ELSE 0 END AS has_2030_target,
    CASE WHEN "Liste des facteurs d’émission (FE) et Pouvoir de Réchauffement Global (PRG) utilisés" IS NOT NULL THEN 1 ELSE 0 END AS has_emission_factors,
    CASE WHEN "Incertitudes" IS NOT NULL THEN 1 ELSE 0 END AS has_uncertainty,
    CASE WHEN "Sources" IS NOT NULL THEN 1 ELSE 0 END AS has_sources,

    (
        CASE WHEN (
            COALESCE("Emissions publication P3.1", 0) +
            COALESCE("Emissions publication P3.2", 0) +
            COALESCE("Emissions publication P3.3", 0) +
            COALESCE("Emissions publication P4.1", 0) +
            COALESCE("Emissions publication P4.2", 0) +
            COALESCE("Emissions publication P5.1", 0)
        ) > 0 THEN 2 ELSE 0 END +
        CASE WHEN "Actions et moyens" IS NOT NULL AND LENGTH("Actions et moyens") > 20 THEN 2 ELSE 0 END +
        CASE WHEN "Objectif de réduction pour 2030" IS NOT NULL AND LENGTH("Objectif de réduction pour 2030") > 5 THEN 1 ELSE 0 END +
        CASE WHEN "Liste des facteurs d’émission (FE) et Pouvoir de Réchauffement Global (PRG) utilisés" IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN "Incertitudes" IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN "Sources" IS NOT NULL THEN 1 ELSE 0 END
    ) AS report_quality_score,

    "Lien URL vers le rapport complet du BEGES"

FROM beges
WHERE "Année de reporting" >= 2022
  AND "Libellé" IN (
    'Ingénierie, études techniques',
    'Conseil pour les affaires et autres conseils de gestion',
    'Analyses, essais et inspections techniques',
    'Activités spécialisées, scientifiques et techniques diverses'
  )
ORDER BY report_quality_score DESC, visible_indirect_emissions DESC
""").df()

quality_candidates.head(50)

,Id,Raison sociale,Type de structure,APE(NAF) associé,Libellé,Année de reporting,staff_count,Mode de consolidation,visible_indirect_emissions,has_action_plan,has_2030_target,has_emission_factors,has_uncertainty,has_sources,report_quality_score,Lien URL vers le rapport complet du BEGES
0,0dd8ffd7-5b30-405c-a68a-50a7b605502c,EXCENT FRANCE,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 500 et 999,Opérationnel,6867080.000,1,1,1,1,1,8,NaN
1,7dd0825b-dc24-4a94-99c8-53f00026fb3d,EXCENT FRANCE,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 500 et 999,Opérationnel,6771822.000,1,1,1,1,1,8,NaN
2,4fb3a4f9-e615-4ac3-952d-743a4bdf3fd3,Clariane,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2023,60000,Opérationnel,489788.700,1,1,1,1,1,8,Le BEGES 2023 a été publié dans l'URD 2024 du ...
3,1d9acfee-ef13-4fdd-971f-245bde451611,Clariane,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,63086,Opérationnel,442526.000,1,1,1,1,1,8,"Publication au sein de l'URD 2024 du Groupe, e..."
4,424b82d5-3e48-4cc0-b52f-ad3d00b813b6,CGX AERO,Entreprise,7112B,"Ingénierie, études techniques",2023,70,Opérationnel,388197.000,1,1,1,1,1,8,NaN
5,e158bbd3-b40d-4dc4-9071-7bb9d391dad0,BEG INGENIERIE,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 100 et 199,Opérationnel,154684.000,1,1,1,1,1,8,NaN
6,4f00070e-408e-4a86-a519-59c1bb6be503,EPSA,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,2274,Opérationnel,26724.000,1,1,1,1,1,8,NaN
7,2e265c3e-1ed3-4a64-a1f8-9d3b2937b72a,REFLEX CES,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 50 et 99,Opérationnel,13035.000,1,1,1,1,1,8,NaN
8,160374fb-92ed-4227-ad2d-e5e0b6d60cc2,ARTELIA,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,Opérationnel,12938.000,1,1,1,1,1,8,NaN
9,5d3d794b-a3f8-4e63-85ef-578ed446de4a,GINGER CEBTP,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,Opérationnel,12926.000,1,1,1,1,1,8,NaN
10,267a82fd-d963-4cc7-b0ef-4e2ac0859f52,MOONGY,Entreprise,7112B,"Ingénierie, études techniques",2024,2887,Opérationnel,7990.900,1,1,1,1,1,8,NaN
11,b831499c-2531-4184-91ab-def008b3a614,LID TECHNOLOGIES,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 50 et 99,Opérationnel,7858.630,1,1,1,1,1,8,NaN
12,5241ed0c-c2af-49b1-9744-d78d31a4190d,EXCENT FRANCE,Entreprise,7112B,"Ingénierie, études techniques",2024,652,Opérationnel,6859.380,1,1,1,1,1,8,NaN
13,145111ee-0ded-421c-af95-5298c6327fcf,RKF GROUP,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2023,Entre 50 et 99,Opérationnel,6587.900,1,1,1,1,1,8,NaN
14,026ab04a-59fa-453e-8693-5d0fcf281f91,BUREAU VERITAS EXPLOITATION,Entreprise,7120B,"Analyses, essais et inspections techniques",2023,Entre 2 000 et 4 999,Opérationnel,6560.000,1,1,1,1,1,8,NaN
15,7a0b6f91-9d03-4851-a2cc-9f2ab53b21d5,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,7120B,"Analyses, essais et inspections techniques",2024,890,Opérationnel,6453.000,1,1,1,1,1,8,NaN
16,b646e185-9c12-4d62-9dc3-5500792bdce7,DEVOTEAM,Entreprise,7112B,"Ingénierie, études techniques",2024,10171,Opérationnel,5804.120,1,1,1,1,1,8,https://devo.team/sustainability-report-2024
17,4f0320a4-5695-4b70-8b6f-dc2de9ec3bf1,cg2i,Entreprise,7112B,"Ingénierie, études techniques",2023,70,Opérationnel,5349.000,1,1,1,1,1,8,NaN
18,398ee6d1-e52b-4158-bf48-785e3b655313,FONDASOL,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 500 et 999,Opérationnel,4355.000,1,1,1,1,1,8,document téléchargé
19,4103d7f9-088c-4a42-8da0-216b5d758007,REDBRIDGE FRANCE SAS,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,47,Opérationnel,3642.000,1,1,1,1,1,8,NaN
20,11b60a93-ffa1-49c4-82d0-d8b3e242162b,INSTITUT TECHNIQUE GAZ ET AIR,Entreprise,7120B,"Analyses, essais et inspections techniques",2022,Entre 500 et 999,Opérationnel,3250.000,1,1,1,1,1,8,/
21,58576edb-a801-43bc-8d40-b952e56c425a,BERTRANDT,Entreprise,7112B,"Ingénierie, études techniques",2024,970,Opérationnel,3079.350,1,1,1,1,1,8,Pas concerné
22,0a439cc4-9f15-4a98-b41a-87c2c866c883,Cegos,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2023,Entre 250 et 499,Opérationnel,2355.000,1,1,1,1,1,8,NaN
23,84cf2342-61ef-4bcc-82a7-ebbdddef5c11,EVERAXIS SAS,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2023,306,Opérationnel,2282.000,1,1,1,1,1,8,NaN
24,8f56c04a-5d32-40b6-92fe-0d32f1283bb1,BUREAU ALPES CONTROLES,Entreprise,7120B,"Analyses, essais et inspections techniques",2024,907,Opérationnel,2257.000,1,1,1,1,1,8,https://app.powerbi.com/Redirect?action=OpenRe...
25,2516af45-b25c-44cd-966f-894ad77ba834,BEE ENGINEERING,Entreprise,7112B,"Ingénierie, études techniques",2024,951,Opérationnel,1793.000,1,1,1,1,1,8,NaN
26,74a04fa3-9ad1-45fe-82fd-701f5fba9d12,JPB SYSTEME,Entreprise,7112B,"Ingénierie, études techniques",2023,133,Opérationnel,1649.600,1,1,1,1,1,8,NaN
27,dae49a31-1fec-43c8-9b12-d71d0240059d,Euroelec Smart Energy,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 6 et 9,Opérationnel,1646.500,1,1,1,1,1,8,NaN
28,bc535b82-ab91-4a57-a3d4-864dde6b8a2d,AMARIS FRANCE SAS,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,1135,Financier,1645.820,1,1,1,1,1,8,NaN
29,48162493-9324-4f3c-9726-ca197ced0940,SYSTRA France,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 2 000 et 4 999,Opérationnel,1638.000,1,1,1,1,1,8,NaN
30,16a01174-756d-4af2-a94b-4e817aae89b2,Eco CO2,Entreprise,7490B,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,Opérationnel,1447.730,1,1,1,1,1,8,NaN
31,6637de8b-0a12-42e5-b0cd-1be4816fe8e0,Extia SAS,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,Opérationnel,1304.000,1,1,1,1,1,8,NaN
32,d27419d3-21bf-425f-bc1a-c43534111089,SYSTRA France,Entreprise,7112B,"Ingénierie, études techniques",2024,2073,Opérationnel,1298.000,1,1,1,1,1,8,NaN
33,c81ec8d8-cd09-4e4f-980d-7961cc424eeb,ADDEXPERT,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,12,Opérationnel,1188.000,1,1,1,1,1,8,NaN
34,9c1c982d-1c5b-4c22-b9f7-5528c1d4cc39,DRACULA TECHNOLOGIES,Entreprise,7112B,"Ingénierie, études techniques",2024,Entre 20 et 49,Opérationnel,1057.750,1,1,1,1,1,8,NaN
35,b75e192d-7583-4810-bc52-c131a122325e,GROUPE CABINET MERLIN,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 500 et 999,Opérationnel,961.000,1,1,1,1,1,8,NaN
36,eddc8590-3910-4407-a724-b22647289b6c,TECHNOMAP,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 50 et 99,Opérationnel,571.000,1,1,1,1,1,8,NaN
37,dae3f1f9-1fc6-4263-b3a0-6b52c360bafe,Secure-IC SAS,Entreprise,7112B,"Ingénierie, études techniques",2023,Entre 100 et 199,Opérationnel,497.000,1,1,1,1,1,8,NaN
38,93beb4f3-b1cd-11ed-8fce-005056b7acd1,MYFLEXGROUP SAS,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2022,Entre 50 et 99,Financier,399.000,1,1,1,1,1,8,NaN
39,4d280fac-1cd3-42dd-b3e4-2278ce537b93,Eurogroup Consulting,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2023,Entre 250 et 499,Opérationnel,375.000,1,1,1,1,1,8,NaN
40,e2330e54-0e41-46c0-8d83-ee9d9791b424,Groupe Référence,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,116,Opérationnel,347.000,1,1,1,1,1,8,NaN
41,f9e9f38f-a69b-4f31-be33-7b05a857cae8,Eurogroup Consulting,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,328,Opérationnel,335.000,1,1,1,1,1,8,file:///C:/Users/TAILLENS/OneDrive%20-%20Eurog...
42,3f2e0573-a8dd-4d9e-9113-95e49e6b3407,EXTIA INGENIERIE SAS,Entreprise,7112B,"Ingénierie, études techniques",2024,328,Opérationnel,309.000,1,1,1,1,1,8,NaN
43,9ae3c38a-c0fd-4a1b-8d05-bea275721473,COORDEF INGENIERIE,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 20 et 49,Opérationnel,306.880,1,1,1,1,1,8,NaN
44,3225f09d-2cb4-41af-bfa7-b58a918484e1,CMULTISERV,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,72,Opérationnel,288.657,1,1,1,1,1,8,NaN
45,050f8054-0070-4f49-b61f-3690a4f919fa,Daveo,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 250 et 499,Opérationnel,287.000,1,1,1,1,1,8,NaN
46,ea530181-9a15-4e74-91b5-e0f5666e9c83,Alltech Consulting,Entreprise,7490B,"Activités spécialisées, scientifiques et techn...",2024,138,Opérationnel,231.260,1,1,1,1,1,8,NaN
47,49efe2a6-3a31-4a64-afcb-0195c554bc36,BEELIX,Entreprise,7022Z,Conseil pour les affaires et autres conseils d...,2024,185,Opérationnel,215.000,1,1,1,1,1,8,NaN
48,9bc949b4-8231-44d2-8523-379df577a13a,QUADRIM,Entreprise,7112B,"Ingénierie, études techniques",2022,Entre 50 et 99,Opérationnel,207.100,1,1,1,1,1,8,https://www.quadrim.com/nos-engagements/
49,65ed5c2d-30ae-4fad-a9de-37845a7dec33,TÜV SÜD France,Entreprise,7120B,"Analyses, essais et inspections techniques",2024,75,Opérationnel,172.200,1,1,1,1,1,8,NaN

In [51]:
quality_candidates[
    [
        "Raison sociale",
        "Type de structure",
        "Libellé",
        "Année de reporting",
        "staff_count",
        "visible_indirect_emissions",
        "has_action_plan",
        "has_2030_target",
        "has_emission_factors",
        "has_uncertainty",
        "has_sources",
        "report_quality_score"
    ]
].head(49)

,Raison sociale,Type de structure,Libellé,Année de reporting,staff_count,visible_indirect_emissions,has_action_plan,has_2030_target,has_emission_factors,has_uncertainty,has_sources,report_quality_score
0,EXCENT FRANCE,Entreprise,"Ingénierie, études techniques",2023,Entre 500 et 999,6867080.000,1,1,1,1,1,8
1,EXCENT FRANCE,Entreprise,"Ingénierie, études techniques",2022,Entre 500 et 999,6771822.000,1,1,1,1,1,8
2,Clariane,Entreprise,Conseil pour les affaires et autres conseils d...,2023,60000,489788.700,1,1,1,1,1,8
3,Clariane,Entreprise,Conseil pour les affaires et autres conseils d...,2024,63086,442526.000,1,1,1,1,1,8
4,CGX AERO,Entreprise,"Ingénierie, études techniques",2023,70,388197.000,1,1,1,1,1,8
5,BEG INGENIERIE,Entreprise,"Ingénierie, études techniques",2023,Entre 100 et 199,154684.000,1,1,1,1,1,8
6,EPSA,Entreprise,Conseil pour les affaires et autres conseils d...,2024,2274,26724.000,1,1,1,1,1,8
7,REFLEX CES,Entreprise,"Ingénierie, études techniques",2022,Entre 50 et 99,13035.000,1,1,1,1,1,8
8,ARTELIA,Entreprise,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,12938.000,1,1,1,1,1,8
9,GINGER CEBTP,Entreprise,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,12926.000,1,1,1,1,1,8
10,MOONGY,Entreprise,"Ingénierie, études techniques",2024,2887,7990.900,1,1,1,1,1,8
11,LID TECHNOLOGIES,Entreprise,"Ingénierie, études techniques",2023,Entre 50 et 99,7858.630,1,1,1,1,1,8
12,EXCENT FRANCE,Entreprise,"Ingénierie, études techniques",2024,652,6859.380,1,1,1,1,1,8
13,RKF GROUP,Entreprise,Conseil pour les affaires et autres conseils d...,2023,Entre 50 et 99,6587.900,1,1,1,1,1,8
14,BUREAU VERITAS EXPLOITATION,Entreprise,"Analyses, essais et inspections techniques",2023,Entre 2 000 et 4 999,6560.000,1,1,1,1,1,8
15,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,Entreprise,"Analyses, essais et inspections techniques",2024,890,6453.000,1,1,1,1,1,8
16,DEVOTEAM,Entreprise,"Ingénierie, études techniques",2024,10171,5804.120,1,1,1,1,1,8
17,cg2i,Entreprise,"Ingénierie, études techniques",2023,70,5349.000,1,1,1,1,1,8
18,FONDASOL,Entreprise,"Ingénierie, études techniques",2023,Entre 500 et 999,4355.000,1,1,1,1,1,8
19,REDBRIDGE FRANCE SAS,Entreprise,Conseil pour les affaires et autres conseils d...,2024,47,3642.000,1,1,1,1,1,8
20,INSTITUT TECHNIQUE GAZ ET AIR,Entreprise,"Analyses, essais et inspections techniques",2022,Entre 500 et 999,3250.000,1,1,1,1,1,8
21,BERTRANDT,Entreprise,"Ingénierie, études techniques",2024,970,3079.350,1,1,1,1,1,8
22,Cegos,Entreprise,Conseil pour les affaires et autres conseils d...,2023,Entre 250 et 499,2355.000,1,1,1,1,1,8
23,EVERAXIS SAS,Entreprise,Conseil pour les affaires et autres conseils d...,2023,306,2282.000,1,1,1,1,1,8
24,BUREAU ALPES CONTROLES,Entreprise,"Analyses, essais et inspections techniques",2024,907,2257.000,1,1,1,1,1,8
25,BEE ENGINEERING,Entreprise,"Ingénierie, études techniques",2024,951,1793.000,1,1,1,1,1,8
26,JPB SYSTEME,Entreprise,"Ingénierie, études techniques",2023,133,1649.600,1,1,1,1,1,8
27,Euroelec Smart Energy,Entreprise,"Ingénierie, études techniques",2023,Entre 6 et 9,1646.500,1,1,1,1,1,8
28,AMARIS FRANCE SAS,Entreprise,Conseil pour les affaires et autres conseils d...,2024,1135,1645.820,1,1,1,1,1,8
29,SYSTRA France,Entreprise,"Ingénierie, études techniques",2023,Entre 2 000 et 4 999,1638.000,1,1,1,1,1,8
30,Eco CO2,Entreprise,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,1447.730,1,1,1,1,1,8
31,Extia SAS,Entreprise,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,1304.000,1,1,1,1,1,8
32,SYSTRA France,Entreprise,"Ingénierie, études techniques",2024,2073,1298.000,1,1,1,1,1,8
33,ADDEXPERT,Entreprise,Conseil pour les affaires et autres conseils d...,2024,12,1188.000,1,1,1,1,1,8
34,DRACULA TECHNOLOGIES,Entreprise,"Ingénierie, études techniques",2024,Entre 20 et 49,1057.750,1,1,1,1,1,8
35,GROUPE CABINET MERLIN,Entreprise,"Ingénierie, études techniques",2022,Entre 500 et 999,961.000,1,1,1,1,1,8
36,TECHNOMAP,Entreprise,"Ingénierie, études techniques",2023,Entre 50 et 99,571.000,1,1,1,1,1,8
37,Secure-IC SAS,Entreprise,"Ingénierie, études techniques",2023,Entre 100 et 199,497.000,1,1,1,1,1,8
38,MYFLEXGROUP SAS,Entreprise,Conseil pour les affaires et autres conseils d...,2022,Entre 50 et 99,399.000,1,1,1,1,1,8
39,Eurogroup Consulting,Entreprise,Conseil pour les affaires et autres conseils d...,2023,Entre 250 et 499,375.000,1,1,1,1,1,8
40,Groupe Référence,Entreprise,Conseil pour les affaires et autres conseils d...,2024,116,347.000,1,1,1,1,1,8
41,Eurogroup Consulting,Entreprise,Conseil pour les affaires et autres conseils d...,2024,328,335.000,1,1,1,1,1,8
42,EXTIA INGENIERIE SAS,Entreprise,"Ingénierie, études techniques",2024,328,309.000,1,1,1,1,1,8
43,COORDEF INGENIERIE,Entreprise,"Ingénierie, études techniques",2022,Entre 20 et 49,306.880,1,1,1,1,1,8
44,CMULTISERV,Entreprise,Conseil pour les affaires et autres conseils d...,2024,72,288.657,1,1,1,1,1,8
45,Daveo,Entreprise,"Ingénierie, études techniques",2022,Entre 250 et 499,287.000,1,1,1,1,1,8
46,Alltech Consulting,Entreprise,"Activités spécialisées, scientifiques et techn...",2024,138,231.260,1,1,1,1,1,8
47,BEELIX,Entreprise,Conseil pour les affaires et autres conseils d...,2024,185,215.000,1,1,1,1,1,8
48,QUADRIM,Entreprise,"Ingénierie, études techniques",2022,Entre 50 et 99,207.100,1,1,1,1,1,8

## Inspect organization descriptions

This block reviews the organization descriptions for high-quality candidate reports.

The purpose is to understand what each organization actually does before selecting the final three firms. This prevents the project from choosing firms only because their BEGES reports are complete, while ignoring whether their activities are relevant to environmental, sustainability, carbon, or technical advisory work.

In [53]:
conn.register("quality_candidates", quality_candidates)

org_descriptions = conn.sql("""
SELECT
    q."Raison sociale",
    q."Libellé",
    q."Année de reporting",
    q.staff_count,
    q.visible_indirect_emissions,
    q.report_quality_score,
    b."Présentation de l'organisation"
FROM quality_candidates q
LEFT JOIN beges b
    ON q."Id" = b."Id"
WHERE q."Raison sociale" IN (
    'ARTELIA',
    'GINGER CEBTP',
    'BUREAU VERITAS EXPLOITATION',
    'CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIENE DE LYON',
    'Eco CO2',
    'SYSTRA France',
    'SOCOTEC',
    'ANTEA FRANCE',
    'ECOCERT SA'
)
ORDER BY q.report_quality_score DESC, q.visible_indirect_emissions DESC
""").df()

org_descriptions

,Raison sociale,Libellé,Année de reporting,staff_count,visible_indirect_emissions,report_quality_score,Présentation de l'organisation
0,ARTELIA,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,12938.00,8,"Artelia, une ingénierie indépendante &amp; mul..."
1,GINGER CEBTP,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,12926.00,8,GINGER CEBTP est un groupe spécialisé dans l’i...
2,BUREAU VERITAS EXPLOITATION,"Analyses, essais et inspections techniques",2023,Entre 2 000 et 4 999,6560.00,8,En tant qu’entreprise de services « Business t...
3,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIEN...,"Analyses, essais et inspections techniques",2024,890,6453.00,8,"CARSO LSEHL, basé à Vénissieux (69), est un de..."
4,SYSTRA France,"Ingénierie, études techniques",2023,Entre 2 000 et 4 999,1638.00,8,SYSTRA est l’un des leaders mondiaux d’ingénie...
5,Eco CO2,"Activités spécialisées, scientifiques et techn...",2023,Entre 100 et 199,1447.73,8,Eco CO2 accompagne les entreprises et les coll...
6,SYSTRA France,"Ingénierie, études techniques",2024,2073,1298.00,8,SYSTRA est l’un des premiers groupes mondiaux ...
7,ECOCERT SA,"Analyses, essais et inspections techniques",2024,778,1242.70,7,"Depuis plus de 30 ans, nous accompagnons de no..."
8,ANTEA FRANCE,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,3179.10,6,Nos équipes composées de 1 000 collaborateurs ...
9,SYSTRA France,"Ingénierie, études techniques",2022,Entre 2 000 et 4 999,1695.00,5,SYSTRA est l’un des leaders mondiaux d’ingénie...

In [54]:
pd.set_option("display.max_colwidth", 500)

org_descriptions[
    [
        "Raison sociale",
        "Libellé",
        "Année de reporting",
        "staff_count",
        "visible_indirect_emissions",
        "Présentation de l'organisation"
    ]
]

,Raison sociale,Libellé,Année de reporting,staff_count,visible_indirect_emissions,Présentation de l'organisation
0,ARTELIA,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,12938.00,"Artelia, une ingénierie indépendante &amp; multidisciplinaireUn accompagnement sur l’ensemble du cycle de vie de votre projetAssociant de fortes compétences en ingénierie de la mobilité, de l’eau, de l’énergie, du bâtiment et de l’industrie, Artelia offre une gamme complète de services, de l’expertise à la livraison de projets complexes : consulting, études et schémas directeurs, management de projet, maîtrise d’œuvre de conception et d’exécution, gestion patrimoniale et marchés globaux. Ave..."
1,GINGER CEBTP,"Ingénierie, études techniques",2022,Entre 1 000 et 1 999,12926.00,"GINGER CEBTP est un groupe spécialisé dans l’ingénierie des sols, des matériaux et des ouvrages. Il intervient en tant que bureau d’étude auprès de tous les acteurs de la construction dans l’accompagnement des projets des plus simples aux plus complexes. Tout au long du cycle de vie d’un ouvrage quel qu’il soit, GINGER CEBTP offre une prise en charge globale des missions d’expertises en se positionnant sur une chaîne de valeur unique :"
2,BUREAU VERITAS EXPLOITATION,"Analyses, essais et inspections techniques",2023,Entre 2 000 et 4 999,6560.00,"En tant qu’entreprise de services « Business to Business to Society », nous établissons une relation de confiance entre entreprises, pouvoirs publics et consommateurs. Nous répondons, à travers cette mission, aux défis sociétaux et environnementaux majeurs de notre époque. Notre mission consiste à réduire les risques de nos clients, à améliorer leurs performances et à soutenir leurs efforts d&#039;innovation. Et ce, en tenant compte de leurs obligations normatives, en matière de qualité, de ..."
3,CARSO - LABORATOIRE SANTE ENVIRONNEMENT HYGIENE DE LYON,"Analyses, essais et inspections techniques",2024,890,6453.00,"CARSO LSEHL, basé à Vénissieux (69), est un des acteurs clef Français de l’analyse environnementale, pharmaceutique et agroalimentaire. L’entreprise, forte de ses 900 collaborateurs, est organisée autour de 4 grands blocs : les laboratoires, les prélèvements, le support à la production et les services généraux. Les équipes de prélèvements jouent un rôle crucial, réalisant une grande partie des prélèvements en environnement et en hygiène hospitalière. Ces opérations , souvent techniques et co..."
4,SYSTRA France,"Ingénierie, études techniques",2023,Entre 2 000 et 4 999,1638.00,"SYSTRA est l’un des leaders mondiaux d’ingénierie et de conseil spécialisés dans les transports publics et les solutions de mobilité. Depuis plus de 60 ans, le Groupe s’engage auprès des villes et des territoires pour contribuer à leur développement en créant, améliorant et modernisant leurs infrastructures et systèmes de transport.En tant qu&#039;acteur de la transition énergétique, SYSTRA propose à ses clients des solutions et des services couvrant l&#039;ensemble du cycle de vie des proje..."
5,Eco CO2,"Activités spécialisées, scientifiques et techniques diverses",2023,Entre 100 et 199,1447.73,"Eco CO2 accompagne les entreprises et les collectivités dans leurs pratiques environnementales, sociales et de gouvernance pour construire un nouveau modèle économique performant et responsable.Notre expertise en mobilité et transportAux côtés de l’ADEME et des organisations professionnelles du secteur, Eco CO2 aide les entreprises et les collectivités dans la réduction de leur impact environnemental, la transition vers la logistique durable, le report modal, et le développement des mobilité..."
6,SYSTRA France,"Ingénierie, études techniques",2024,2073,1298.00,"SYSTRA est l’un des premiers groupes mondiaux d’ingénierie et de conseil spécialisés dans les transports publics et les solutions de mobilité. Depuis plus de 65 ans, le Groupe s’engage auprès des villes et des territoires pour contribuer à leur développement en créant, améliorant et modernisant leurs infrastructures et systèmes de transport."
7,ECOCERT SA,"Analyses, essais et inspections techniques",2024,778,1242.70,"Depuis plus de 30 ans, nous accompagnons de nombreux acteurs dans le déploiement et la valorisation de pratiques durables à travers la certification, le conseil et la formation. Engagé dès sa création pour l’agriculture biologique, Ecocert a aujourd&#039;hui étendu son action à de nombreuses filières dans le monde Notre mission : Agir pour un monde durable en accompagnant la transition vers des modèles économiques plus juste et qui préservent la santé, le climat et la biodiversité à travers ..."
8,ANTEA FRANCE,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,3179.10,"Nos équipes composées de 1 000 collaborateurs et réparties dans 25 implantations en métropole et 5 en Départements d’Outre-Mer, interviennent au cœur des territoires et aux côtés des acteurs locaux en France métropolitaine, dans les DOM et à l’international.Nous sommes présents auprès d’une clientèle très diversifiée, constituée de grands groupes industriels, de PME dynamiques, de collectivités locales ou de gouvernements. A tous, nous avons à cœur de répondre avec le même engagement et la m..."
9,SYSTRA France,"Ingénierie, études techniques",2022,Entre 2 000 et 4 999,1695.00,"SYSTRA est l’un des leaders mondiaux d’ingénierie et de conseil spécialisés dans les transports publics et les solutions de mobilité. Depuis plus de 60 ans, le Groupe s’engage auprès des villes et des territoires pour contribuer à leur développement en créant, améliorant et modernisant leurs infrastructures et systèmes de transport.En tant qu&#039;acteur de la transition énergétique, SYSTRA propose à ses clients des solutions et des services couvrant l&#039;ensemble du cycle de vie des proje..."

## Select final firms for detailed analysis

This block defines the final firm set for the project.

The selected organizations represent five related but distinct environmental and sustainability archetypes: environmental engineering, technical consulting, compliance and inspection, sustainability certification, and ecological transition advisory.

This selection allows the project to compare not only emissions totals, but also differences in reporting quality, Scope 3 coverage, methodological transparency, and transition-plan detail across organizations whose public missions are connected to environmental performance.

In [55]:
selected_firms = org_descriptions[
    org_descriptions["Raison sociale"].isin([
        "ARTELIA",
        "ANTEA FRANCE",
        "BUREAU VERITAS EXPLOITATION",
        "ECOCERT SA",
        "Eco CO2"
    ])
].copy()

selected_firms

,Raison sociale,Libellé,Année de reporting,staff_count,visible_indirect_emissions,report_quality_score,Présentation de l'organisation
0,ARTELIA,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,12938.00,8,"Artelia, une ingénierie indépendante &amp; multidisciplinaireUn accompagnement sur l’ensemble du cycle de vie de votre projetAssociant de fortes compétences en ingénierie de la mobilité, de l’eau, de l’énergie, du bâtiment et de l’industrie, Artelia offre une gamme complète de services, de l’expertise à la livraison de projets complexes : consulting, études et schémas directeurs, management de projet, maîtrise d’œuvre de conception et d’exécution, gestion patrimoniale et marchés globaux. Ave..."
2,BUREAU VERITAS EXPLOITATION,"Analyses, essais et inspections techniques",2023,Entre 2 000 et 4 999,6560.00,8,"En tant qu’entreprise de services « Business to Business to Society », nous établissons une relation de confiance entre entreprises, pouvoirs publics et consommateurs. Nous répondons, à travers cette mission, aux défis sociétaux et environnementaux majeurs de notre époque. Notre mission consiste à réduire les risques de nos clients, à améliorer leurs performances et à soutenir leurs efforts d&#039;innovation. Et ce, en tenant compte de leurs obligations normatives, en matière de qualité, de ..."
5,Eco CO2,"Activités spécialisées, scientifiques et techniques diverses",2023,Entre 100 et 199,1447.73,8,"Eco CO2 accompagne les entreprises et les collectivités dans leurs pratiques environnementales, sociales et de gouvernance pour construire un nouveau modèle économique performant et responsable.Notre expertise en mobilité et transportAux côtés de l’ADEME et des organisations professionnelles du secteur, Eco CO2 aide les entreprises et les collectivités dans la réduction de leur impact environnemental, la transition vers la logistique durable, le report modal, et le développement des mobilité..."
7,ECOCERT SA,"Analyses, essais et inspections techniques",2024,778,1242.70,7,"Depuis plus de 30 ans, nous accompagnons de nombreux acteurs dans le déploiement et la valorisation de pratiques durables à travers la certification, le conseil et la formation. Engagé dès sa création pour l’agriculture biologique, Ecocert a aujourd&#039;hui étendu son action à de nombreuses filières dans le monde Notre mission : Agir pour un monde durable en accompagnant la transition vers des modèles économiques plus juste et qui préservent la santé, le climat et la biodiversité à travers ..."
8,ANTEA FRANCE,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,3179.10,6,"Nos équipes composées de 1 000 collaborateurs et réparties dans 25 implantations en métropole et 5 en Départements d’Outre-Mer, interviennent au cœur des territoires et aux côtés des acteurs locaux en France métropolitaine, dans les DOM et à l’international.Nous sommes présents auprès d’une clientèle très diversifiée, constituée de grands groupes industriels, de PME dynamiques, de collectivités locales ou de gouvernements. A tous, nous avons à cœur de répondre avec le même engagement et la m..."

In [56]:
selected_firms = org_descriptions[
    org_descriptions["Raison sociale"].isin([
        "ARTELIA",
        "ANTEA FRANCE",
        "BUREAU VERITAS EXPLOITATION",
        "ECOCERT SA",
        "Eco CO2"
    ])
].copy()

selected_firms = (
    selected_firms
    .sort_values(["Raison sociale", "Année de reporting"], ascending=[True, False])
    .drop_duplicates(subset=["Raison sociale"], keep="first")
)

selected_firms

,Raison sociale,Libellé,Année de reporting,staff_count,visible_indirect_emissions,report_quality_score,Présentation de l'organisation
8,ANTEA FRANCE,"Ingénierie, études techniques",2023,Entre 1 000 et 1 999,3179.10,6,"Nos équipes composées de 1 000 collaborateurs et réparties dans 25 implantations en métropole et 5 en Départements d’Outre-Mer, interviennent au cœur des territoires et aux côtés des acteurs locaux en France métropolitaine, dans les DOM et à l’international.Nous sommes présents auprès d’une clientèle très diversifiée, constituée de grands groupes industriels, de PME dynamiques, de collectivités locales ou de gouvernements. A tous, nous avons à cœur de répondre avec le même engagement et la m..."
0,ARTELIA,"Ingénierie, études techniques",2022,Entre 5 000 et 9 999,12938.00,8,"Artelia, une ingénierie indépendante &amp; multidisciplinaireUn accompagnement sur l’ensemble du cycle de vie de votre projetAssociant de fortes compétences en ingénierie de la mobilité, de l’eau, de l’énergie, du bâtiment et de l’industrie, Artelia offre une gamme complète de services, de l’expertise à la livraison de projets complexes : consulting, études et schémas directeurs, management de projet, maîtrise d’œuvre de conception et d’exécution, gestion patrimoniale et marchés globaux. Ave..."
2,BUREAU VERITAS EXPLOITATION,"Analyses, essais et inspections techniques",2023,Entre 2 000 et 4 999,6560.00,8,"En tant qu’entreprise de services « Business to Business to Society », nous établissons une relation de confiance entre entreprises, pouvoirs publics et consommateurs. Nous répondons, à travers cette mission, aux défis sociétaux et environnementaux majeurs de notre époque. Notre mission consiste à réduire les risques de nos clients, à améliorer leurs performances et à soutenir leurs efforts d&#039;innovation. Et ce, en tenant compte de leurs obligations normatives, en matière de qualité, de ..."
7,ECOCERT SA,"Analyses, essais et inspections techniques",2024,778,1242.70,7,"Depuis plus de 30 ans, nous accompagnons de nombreux acteurs dans le déploiement et la valorisation de pratiques durables à travers la certification, le conseil et la formation. Engagé dès sa création pour l’agriculture biologique, Ecocert a aujourd&#039;hui étendu son action à de nombreuses filières dans le monde Notre mission : Agir pour un monde durable en accompagnant la transition vers des modèles économiques plus juste et qui préservent la santé, le climat et la biodiversité à travers ..."
5,Eco CO2,"Activités spécialisées, scientifiques et techniques diverses",2023,Entre 100 et 199,1447.73,8,"Eco CO2 accompagne les entreprises et les collectivités dans leurs pratiques environnementales, sociales et de gouvernance pour construire un nouveau modèle économique performant et responsable.Notre expertise en mobilité et transportAux côtés de l’ADEME et des organisations professionnelles du secteur, Eco CO2 aide les entreprises et les collectivités dans la réduction de leur impact environnemental, la transition vers la logistique durable, le report modal, et le développement des mobilité..."

## Save selected firm list

This block saves the final selected firms as a processed CSV file.

This creates a reproducible checkpoint for the project. Downstream notebooks can load this selected firm list directly instead of repeating the firm-selection logic.

In [58]:
processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

selected_firms.to_csv(processed_dir / "selected_firms.csv", index=False)

print("Saved selected_firms.csv")

Saved selected_firms.csv

## Firm selection summary

The final selected firms are:

ARTELIA

ANTEA FRANCE

BUREAU VERITAS EXPLOITATION

ECOCERT SA

Eco CO2

These firms were selected because they represent complementary environmental and sustainability-related organization types:

ARTELIA and ANTEA FRANCE represent environmental and multidisciplinary engineering consulting.

BUREAU VERITAS EXPLOITATION represents inspection, compliance, risk management, and certification.

ECOCERT SA represents sustainability certification, consulting, and training.

Eco CO2 represents ecological transition, ESG practices, mobility, and climate advisory.

Together, these organizations provide a strong basis for comparing greenhouse gas inventory structure, Scope 3 coverage, methodological transparency, and transition-plan quality across firms whose public missions are connected to environmental performance.

In [59]:
selected_ids = selected_firms["Raison sociale"].tolist()

scope_check = conn.sql("""
SELECT
    "Raison sociale",
    "Année de reporting",

    COALESCE("Emissions publication P3.1", 0) AS p3_1,
    COALESCE("Emissions publication P3.2", 0) AS p3_2,
    COALESCE("Emissions publication P3.3", 0) AS p3_3,
    COALESCE("Emissions publication P3.4", 0) AS p3_4,
    COALESCE("Emissions publication P3.5", 0) AS p3_5,

    COALESCE("Emissions publication P4.1", 0) AS p4_1,
    COALESCE("Emissions publication P4.2", 0) AS p4_2,
    COALESCE("Emissions publication P4.3", 0) AS p4_3,
    COALESCE("Emissions publication P4.4", 0) AS p4_4,
    COALESCE("Emissions publication P4.5", 0) AS p4_5,

    COALESCE("Emissions publication P5.1", 0) AS p5_1,
    COALESCE("Emissions publication P5.2", 0) AS p5_2,
    COALESCE("Emissions publication P5.3", 0) AS p5_3,
    COALESCE("Emissions publication P5.4", 0) AS p5_4,

    (
        COALESCE("Emissions publication P3.1", 0) +
        COALESCE("Emissions publication P3.2", 0) +
        COALESCE("Emissions publication P3.3", 0) +
        COALESCE("Emissions publication P3.4", 0) +
        COALESCE("Emissions publication P3.5", 0) +
        COALESCE("Emissions publication P4.1", 0) +
        COALESCE("Emissions publication P4.2", 0) +
        COALESCE("Emissions publication P4.3", 0) +
        COALESCE("Emissions publication P4.4", 0) +
        COALESCE("Emissions publication P4.5", 0) +
        COALESCE("Emissions publication P5.1", 0) +
        COALESCE("Emissions publication P5.2", 0) +
        COALESCE("Emissions publication P5.3", 0) +
        COALESCE("Emissions publication P5.4", 0)
    ) AS total_indirect_emissions

FROM beges
WHERE "Raison sociale" IN (
    'ARTELIA',
    'ANTEA FRANCE',
    'BUREAU VERITAS EXPLOITATION',
    'ECOCERT SA',
    'Eco CO2'
)
ORDER BY "Raison sociale", "Année de reporting" DESC
""").df()

scope_check

,Raison sociale,Année de reporting,p3_1,p3_2,p3_3,p3_4,p3_5,p4_1,p4_2,p4_3,p4_4,p4_5,p5_1,p5_2,p5_3,p5_4,total_indirect_emissions
0,ANTEA FRANCE,2023,11.50,0.0,552.90,0.0,119.60,1283.30,1331.40,63.70,1315.5,8162.90,0.00,0.0,0.00,0.0,12840.80
1,ANTEA FRANCE,2019,0.00,24.0,743.00,0.0,280.00,7652.00,1045.00,0.00,0.0,0.00,0.00,0.0,0.00,0.0,9744.00
2,ARTELIA,2022,0.00,0.0,5925.00,0.0,4968.00,1966.00,5047.00,38.00,0.0,0.00,0.00,0.0,0.00,0.0,17944.00
3,BUREAU VERITAS EXPLOITATION,2023,0.00,0.0,1253.00,0.0,0.00,4912.00,395.00,62.00,0.0,16446.00,0.00,0.0,0.00,0.0,23068.00
4,BUREAU VERITAS EXPLOITATION,2019,0.00,0.0,0.00,0.0,1455.00,2.00,0.00,62.00,0.0,0.00,0.00,0.0,0.00,0.0,1519.00
5,ECOCERT SA,2024,90.40,0.0,460.50,10.4,551.60,362.00,329.80,0.80,396.4,981.70,0.00,0.0,0.00,0.0,3183.60
6,Eco CO2,2023,0.15,0.0,15.46,0.0,61.85,1353.04,78.63,0.23,0.0,3.48,0.45,0.0,0.63,0.0,1513.92

## Verify indirect emissions coverage

This block verifies that all selected firms report indirect emissions categories in the ADEME BEGES dataset.

This step is necessary because the project depends on comparing Scope 3-type reporting. In the French BEGES structure, the relevant data are reported through indirect emissions categories such as P3, P4, and P5. These categories are not identical to the GHG Protocol Scope 3 categories, but they provide the correct basis for analyzing indirect emissions coverage within the BEGES framework.

In [60]:
scope_check.to_csv(processed_dir / "selected_firms_indirect_emissions_check.csv", index=False)

print("Saved selected_firms_indirect_emissions_check.csv")

Saved selected_firms_indirect_emissions_check.csv